-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-frappe"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { fg = "#fd9761" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#6bc4ea" })
hi(0, "@constructor.lua", { fg = "#fab8b9" })
hi(0, "@constructor.tsx", { fg = "#b8b9ff" })
hi(0, "@constructor.typescript", { fg = "#b8b9ff" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { fg = "#d196f6" })
hi(0, "@field", { fg = "#b8b9ff" })
hi(0, "@field.yaml", { fg = "#83a8ff" })
hi(0, "@function.builtin", { fg = "#fd9761" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#63cdc0" })
hi(0, "@keyword.export", { bold = true, fg = "#7dd6e5" })
hi(0, "@keyword.function", { fg = "#d196f6" })
hi(0, "@keyword.operator", { fg = "#d196f6" })
hi(0, "@keyword.return", { fg = "#d196f6" })
hi(0, "@label.json", { fg = "#83a8ff" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.interface", { fg = "#fab8b9" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@namespace", { fg = "#b8b9ff" })
hi(0, "@number.css", { fg = "#fd9761" })
hi(0, "@parameter", { fg = "#fa8f94" })
hi(0, "@property", { fg = "#b8b9ff" })
hi(0, "@property.class.css", { fg = "#efc672" })
hi(0, "@property.cpp", { fg = "#fbd2c9" })
hi(0, "@property.css", { fg = "#b8b9ff" })
hi(0, "@property.id.css", { fg = "#83a8ff" })
hi(0, "@property.toml", { fg = "#83a8ff" })
hi(0, "@punctuation.bracket", { fg = "#8d9ad0" })
hi(0, "@punctuation.delimiter", { fg = "#8d9ad0" })
hi(0, "@punctuation.special", { fg = "#7dd6e5" })
hi(0, "@string.escape", { fg = "#ffb0eb" })
hi(0, "@string.plain.css", { fg = "#fd9761" })
hi(0, "@string.regex", { fg = "#fd9761" })
hi(0, "@string.special", { fg = "#83a8ff" })
hi(0, "@symbol", { fg = "#fab8b9" })
hi(0, "@symbol.ruby", { fg = "#fab8b9" })
hi(0, "@tag", { fg = "#d196f6" })
hi(0, "@tag.attribute", { fg = "#63cdc0" })
hi(0, "@tag.attribute.tsx", { fg = "#d196f6" })
hi(0, "@tag.delimiter", { fg = "#7dd6e5" })
hi(0, "@text", { fg = "#c3cfff" })
hi(0, "@text.danger", { bg = "#e78284", fg = "#2a315b" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#fa8f94" })
hi(0, "@text.environment", { fg = "#ffb0eb" })
hi(0, "@text.environment.name", { fg = "#83a8ff" })
hi(0, "@text.literal", { fg = "#63cdc0" })
hi(0, "@text.math", { fg = "#83a8ff" })
hi(0, "@text.note", { bg = "#8caaee", fg = "#2a315b" })
hi(0, "@text.reference", { bold = true, fg = "#b8b9ff" })
hi(0, "@text.strike", { fg = "#c3cfff", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#fa8f94" })
hi(0, "@text.title", { bold = true, fg = "#83a8ff" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#e5c890", fg = "#2a315b" })
hi(0, "@text.todo.checked", { fg = "#99d76b" })
hi(0, "@text.todo.unchecked", { fg = "#7b89c0" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.uri", { fg = "#fbd2c9", underline = true })
hi(0, "@text.warning", { bg = "#e5c890", fg = "#2a315b" })
hi(0, "@type.builtin", { fg = "#efc672" })
hi(0, "@type.css", { fg = "#b8b9ff" })
hi(0, "@type.definition", { link = "@type" })
hi(0, "@type.qualifier", { link = "@type" })
hi(0, "@type.qualifier.php", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#d196f6" })
hi(0, "@variable", { fg = "#c3cfff" })
hi(0, "@variable.builtin", { fg = "#f9747a" })
hi(0, "ActionFix", { fg = "#d196f6" })
hi(0, "ActionPreviewBorder", { fg = "#83a8ff" })
hi(0, "ActionPreviewNormal", {})
hi(0, "ActionPreviewTitle", { bold = true, fg = "#83a8ff" })
hi(0, "AlphaButtons", { fg = "#b8b9ff" })
hi(0, "AlphaFooter", { fg = "#efc672" })
hi(0, "AlphaHeader", { fg = "#83a8ff" })
hi(0, "AlphaHeaderLabel", { fg = "#fd9761" })
hi(0, "AlphaShortcut", { fg = "#99d76b" })
hi(0, "Array", { fg = "#b8b9ff" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#fd9761" })
hi(0, "BufferAlternate", {})
hi(0, "BufferAlternateADDED", {})
hi(0, "BufferAlternateCHANGED", {})
hi(0, "BufferAlternateDELETED", {})
hi(0, "BufferAlternateERROR", {})
hi(0, "BufferAlternateHINT", {})
hi(0, "BufferAlternateINFO", {})
hi(0, "BufferAlternateIcon", {})
hi(0, "BufferAlternateIndex", {})
hi(0, "BufferAlternateMod", {})
hi(0, "BufferAlternateNumber", {})
hi(0, "BufferAlternateSign", {})
hi(0, "BufferAlternateSignRight", {})
hi(0, "BufferAlternateTarget", {})
hi(0, "BufferAlternateWARN", {})
hi(0, "BufferCurrent", { bg = "#51576d", ctermfg = 255, fg = "#99d76b" })
hi(0, "BufferCurrentADDED", { bg = "#51576d", ctermfg = 82, fg = "#99d76b" })
hi(0, "BufferCurrentCHANGED", { bg = "#51576d", ctermfg = 75, fg = "#efc672" })
hi(0, "BufferCurrentDELETED", { bg = "#51576d", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferCurrentERROR", { bg = "#51576d", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferCurrentHINT", { bg = "#51576d", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferCurrentINFO", { bg = "#51576d", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferCurrentIcon", { bg = "#51576d", ctermfg = 255, fg = "#99d76b" })
hi(0, "BufferCurrentIndex", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferCurrentMod", { bg = "#51576d", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferCurrentNumber", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferCurrentSign", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferCurrentSignRight", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferCurrentTarget", { bg = "#51576d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferCurrentWARN", { bg = "#51576d", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultAlternateIcon", {})
hi(0, "BufferDefaultAlternateNumber", {})
hi(0, "BufferDefaultAlternateSignRight", {})
hi(0, "BufferDefaultCurrent", { bg = "#51576d", ctermfg = 255, fg = "#99d76b" })
hi(0, "BufferDefaultCurrentADDED", { bg = "#51576d", ctermfg = 82, fg = "#99d76b" })
hi(0, "BufferDefaultCurrentCHANGED", { bg = "#51576d", ctermfg = 75, fg = "#efc672" })
hi(0, "BufferDefaultCurrentDELETED", { bg = "#51576d", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferDefaultCurrentERROR", { bg = "#51576d", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferDefaultCurrentHINT", { bg = "#51576d", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferDefaultCurrentINFO", { bg = "#51576d", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferDefaultCurrentIcon", { bg = "#51576d", ctermfg = 255, fg = "#99d76b" })
hi(0, "BufferDefaultCurrentIndex", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferDefaultCurrentMod", { bg = "#51576d", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferDefaultCurrentNumber", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferDefaultCurrentSign", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferDefaultCurrentSignRight", { bg = "#51576d", ctermfg = 75, fg = "#ffb0eb" })
hi(0, "BufferDefaultCurrentTarget", { bg = "#51576d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultCurrentWARN", { bg = "#51576d", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultInactive", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultInactiveADDED", { bg = "#292c3c", ctermfg = 82, fg = "#99d76b" })
hi(0, "BufferDefaultInactiveCHANGED", { bg = "#292c3c", ctermfg = 75, fg = "#efc672" })
hi(0, "BufferDefaultInactiveDELETED", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferDefaultInactiveERROR", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferDefaultInactiveHINT", { bg = "#292c3c", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferDefaultInactiveINFO", { bg = "#292c3c", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferDefaultInactiveIcon", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultInactiveIndex", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferDefaultInactiveMod", { bg = "#292c3c", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferDefaultInactiveNumber", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferDefaultInactiveSign", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferDefaultInactiveSignRight", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferDefaultInactiveTarget", { bg = "#292c3c", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultInactiveWARN", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultOffset", { ctermfg = 102, fg = "#c3cfff" })
hi(0, "BufferDefaultTabpageFill", { ctermfg = 102, fg = "#c3cfff" })
hi(0, "BufferDefaultTabpages", { bold = true, ctermfg = 75, fg = "#fd9761" })
hi(0, "BufferDefaultTabpagesSep", { bold = true, ctermfg = 255, fg = "#ffb0eb" })
hi(0, "BufferDefaultVisible", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleADDED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultVisibleCHANGED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultVisibleDELETED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferDefaultVisibleERROR", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferDefaultVisibleHINT", { bg = "#292c3c", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferDefaultVisibleINFO", { bg = "#292c3c", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferDefaultVisibleIcon", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleIndex", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleMod", { bg = "#292c3c", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferDefaultVisibleNumber", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleSign", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleSignRight", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferDefaultVisibleTarget", { bg = "#292c3c", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultVisibleWARN", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferInactive", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferInactiveADDED", { bg = "#292c3c", ctermfg = 82, fg = "#99d76b" })
hi(0, "BufferInactiveCHANGED", { bg = "#292c3c", ctermfg = 75, fg = "#efc672" })
hi(0, "BufferInactiveDELETED", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferInactiveERROR", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferInactiveHINT", { bg = "#292c3c", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferInactiveINFO", { bg = "#292c3c", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferInactiveIcon", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferInactiveIndex", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferInactiveMod", { bg = "#292c3c", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferInactiveNumber", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferInactiveSign", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferInactiveSignRight", { bg = "#292c3c", ctermfg = 240, fg = "#6b76b0" })
hi(0, "BufferInactiveTarget", { bg = "#292c3c", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferInactiveWARN", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferOffset", { ctermfg = 102, fg = "#c3cfff" })
hi(0, "BufferScrollArrow", { bold = true, ctermfg = 255, fg = "#ffb0eb" })
hi(0, "BufferTabpageFill", { ctermfg = 102, fg = "#c3cfff" })
hi(0, "BufferTabpages", { bold = true, ctermfg = 75, fg = "#fd9761" })
hi(0, "BufferTabpagesSep", { bold = true, ctermfg = 255, fg = "#ffb0eb" })
hi(0, "BufferVisible", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleADDED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferVisibleCHANGED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferVisibleDELETED", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "BufferVisibleERROR", { bg = "#292c3c", ctermfg = 124, fg = "#f9747a" })
hi(0, "BufferVisibleHINT", { bg = "#292c3c", ctermfg = 168, fg = "#63cdc0" })
hi(0, "BufferVisibleINFO", { bg = "#292c3c", ctermfg = 217, fg = "#7dd6e5" })
hi(0, "BufferVisibleIcon", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleIndex", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleMod", { bg = "#292c3c", ctermfg = 178, fg = "#efc672" })
hi(0, "BufferVisibleNumber", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleSign", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleSignRight", { bg = "#292c3c", ctermfg = 255, fg = "#47538d" })
hi(0, "BufferVisibleTarget", { bg = "#292c3c", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferVisibleWARN", { bg = "#292c3c", ctermfg = 208, fg = "#efc672" })
hi(0, "CallHierarchyBorder", { fg = "#83a8ff" })
hi(0, "CallHierarchyIcon", { fg = "#d196f6" })
hi(0, "CallHierarchyNormal", {})
hi(0, "CallHierarchyTitle", { bold = true, fg = "#83a8ff" })
hi(0, "Character", { fg = "#63cdc0" })
hi(0, "CmpItemAbbr", { fg = "#8d9ad0" })
hi(0, "CmpItemAbbrDefault", { fg = "#8d9ad0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6b76b0", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6b76b0" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#c3cfff" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#8d9ad0" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#c3cfff" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#8d9ad0" })
hi(0, "CmpItemKind", { fg = "#83a8ff" })
hi(0, "CmpItemKindClass", { fg = "#efc672" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#f9747a" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#fd9761" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#83a8ff" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { ctermfg = 6, fg = "#01ff01" })
hi(0, "CmpItemKindDefault", { fg = "#ffb0eb" })
hi(0, "CmpItemKindEnum", { fg = "#99d76b" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#f9747a" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#83a8ff" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#99d76b" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#83a8ff" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#83a8ff" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#83a8ff" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#efc672" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#f9747a" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#83a8ff" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#83a8ff" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#83a8ff" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#99d76b" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#f9747a" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#d196f6" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#83a8ff" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#63cdc0" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#83a8ff" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#99d76b" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#fd9761" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#fab8b9" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#c3cfff" })
hi(0, "CmpItemMenuDefault", { fg = "#8d9ad0" })
hi(0, "CodeActionBorder", { fg = "#83a8ff" })
hi(0, "CodeActionNormal", {})
hi(0, "CodeActionNumber", { bg = "#455052" })
hi(0, "CodeActionText", { fg = "#c3cfff" })
hi(0, "ColorColumn", { bg = "#414559" })
hi(0, "Comment", { fg = "#6b76b0" })
hi(0, "Conceal", { fg = "#7b89c0" })
hi(0, "Conditional", { fg = "#d196f6" })
hi(0, "Constant", { fg = "#fd9761" })
hi(0, "CurSearch", { bg = "#e78284", fg = "#25294e" })
hi(0, "Cursor", { bg = "#c6d0f5", fg = "#2a315b" })
hi(0, "CursorColumn", { bg = "#292c3c" })
hi(0, "CursorIM", { bg = "#c6d0f5", fg = "#2a315b" })
hi(0, "CursorLine", { bg = "#3b3f52" })
hi(0, "CursorLineNr", { fg = "#b8b9ff" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#424242" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsPath", { fg = "#00f1f5" })
hi(0, "DapUIDecoration", { fg = "#00f1f5" })
hi(0, "DapUIFloatBorder", { fg = "#00f1f5" })
hi(0, "DapUILineNumber", { fg = "#00f1f5" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#00f1f5" })
hi(0, "DapUINormalNC", {})
hi(0, "DapUIPlayPause", { fg = "#a5ff5e" })
hi(0, "DapUIPlayPauseNC", { fg = "#a5ff5e" })
hi(0, "DapUIRestart", { fg = "#a5ff5e" })
hi(0, "DapUIRestartNC", { fg = "#a5ff5e" })
hi(0, "DapUIScope", { fg = "#00f1f5" })
hi(0, "DapUISource", { fg = "#d680ff" })
hi(0, "DapUIStepBack", { fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { fg = "#00f1f5" })
hi(0, "DapUIStepInto", { fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOut", { fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOver", { fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { fg = "#00f1f5" })
hi(0, "DapUIStop", { fg = "#f70067" })
hi(0, "DapUIStopNC", { fg = "#f70067" })
hi(0, "DapUIStoppedThread", { fg = "#00f1f5" })
hi(0, "DapUIThread", { fg = "#a5ff5e" })
hi(0, "DapUIType", { fg = "#d680ff" })
hi(0, "DapUIUnavailable", { fg = "#424242" })
hi(0, "DapUIUnavailableNC", { fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { fg = "#f70067" })
hi(0, "DapUIWatchesError", { fg = "#f70067" })
hi(0, "DapUIWatchesValue", { fg = "#a5ff5e" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#99d76b" })
hi(0, "DashboardFiles", { fg = "#b8b9ff" })
hi(0, "DashboardFooter", { fg = "#efc672" })
hi(0, "DashboardHeader", { fg = "#83a8ff" })
hi(0, "DashboardMruTitle", { fg = "#7dd6e5" })
hi(0, "DashboardProjectTitle", { fg = "#7dd6e5" })
hi(0, "DashboardShortCut", { fg = "#ffb0eb" })
hi(0, "DefinitionBorder", { fg = "#83a8ff" })
hi(0, "DefinitionNormal", {})
hi(0, "DefinitionSearch", { bg = "#506373", fg = "#c3cfff" })
hi(0, "DiagnosticBorder", { fg = "#83a8ff" })
hi(0, "DiagnosticBufnr", { fg = "#c3cfff" })
hi(0, "DiagnosticError", { fg = "#f9747a" })
hi(0, "DiagnosticFloatingError", { fg = "#f9747a" })
hi(0, "DiagnosticFloatingHint", { fg = "#63cdc0" })
hi(0, "DiagnosticFloatingInfo", { fg = "#7dd6e5" })
hi(0, "DiagnosticFloatingWarn", { fg = "#efc672" })
hi(0, "DiagnosticFname", { fg = "#d196f6" })
hi(0, "DiagnosticHint", { fg = "#63cdc0" })
hi(0, "DiagnosticInfo", { fg = "#7dd6e5" })
hi(0, "DiagnosticNormal", {})
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#6cf671" })
hi(0, "DiagnosticShowBorder", { fg = "#b8b9ff" })
hi(0, "DiagnosticShowNormal", {})
hi(0, "DiagnosticSignError", { fg = "#f9747a" })
hi(0, "DiagnosticSignHint", { fg = "#63cdc0" })
hi(0, "DiagnosticSignInfo", { fg = "#7dd6e5" })
hi(0, "DiagnosticSignWarn", { fg = "#efc672" })
hi(0, "DiagnosticSource", { fg = "#6b76b0" })
hi(0, "DiagnosticUnderlineError", { sp = "#e78284", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#99d1db", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e5c890", underline = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#f9747a" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#63cdc0" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#7dd6e5" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#efc672" })
hi(0, "DiagnosticWarn", { fg = "#efc672" })
hi(0, "DiffAdd", { bg = "#455052" })
hi(0, "DiffChange", { bg = "#363c52" })
hi(0, "DiffDelete", { bg = "#514251" })
hi(0, "DiffText", { bg = "#4c5778" })
hi(0, "Directory", { fg = "#83a8ff" })
hi(0, "DropBarIconUISeparator", { fg = "#7b89c0" })
hi(0, "DropBarKindArray", { fg = "#c3cfff" })
hi(0, "DropBarKindBoolean", { fg = "#c3cfff" })
hi(0, "DropBarKindBreakStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindCall", { fg = "#c3cfff" })
hi(0, "DropBarKindCaseStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindClass", { fg = "#c3cfff" })
hi(0, "DropBarKindConstant", { fg = "#c3cfff" })
hi(0, "DropBarKindConstructor", { fg = "#c3cfff" })
hi(0, "DropBarKindContinueStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindDeclaration", { fg = "#c3cfff" })
hi(0, "DropBarKindDelete", { fg = "#c3cfff" })
hi(0, "DropBarKindDoStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindElseStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindEnum", { fg = "#c3cfff" })
hi(0, "DropBarKindEnumMember", { fg = "#c3cfff" })
hi(0, "DropBarKindEvent", { fg = "#c3cfff" })
hi(0, "DropBarKindField", { fg = "#c3cfff" })
hi(0, "DropBarKindFile", { fg = "#c3cfff" })
hi(0, "DropBarKindFolder", { fg = "#c3cfff" })
hi(0, "DropBarKindForStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindFunction", { fg = "#c3cfff" })
hi(0, "DropBarKindIdentifier", { fg = "#c3cfff" })
hi(0, "DropBarKindIfStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindInterface", { fg = "#c3cfff" })
hi(0, "DropBarKindKeyword", { fg = "#c3cfff" })
hi(0, "DropBarKindList", { fg = "#c3cfff" })
hi(0, "DropBarKindMacro", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH1", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH2", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH3", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH4", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH5", { fg = "#c3cfff" })
hi(0, "DropBarKindMarkdownH6", { fg = "#c3cfff" })
hi(0, "DropBarKindMethod", { fg = "#c3cfff" })
hi(0, "DropBarKindModule", { fg = "#c3cfff" })
hi(0, "DropBarKindNamespace", { fg = "#c3cfff" })
hi(0, "DropBarKindNull", { fg = "#c3cfff" })
hi(0, "DropBarKindNumber", { fg = "#c3cfff" })
hi(0, "DropBarKindObject", { fg = "#c3cfff" })
hi(0, "DropBarKindOperator", { fg = "#c3cfff" })
hi(0, "DropBarKindPackage", { fg = "#c3cfff" })
hi(0, "DropBarKindProperty", { fg = "#c3cfff" })
hi(0, "DropBarKindReference", { fg = "#c3cfff" })
hi(0, "DropBarKindRepeat", { fg = "#c3cfff" })
hi(0, "DropBarKindScope", { fg = "#c3cfff" })
hi(0, "DropBarKindSpecifier", { fg = "#c3cfff" })
hi(0, "DropBarKindStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindString", { fg = "#c3cfff" })
hi(0, "DropBarKindStruct", { fg = "#c3cfff" })
hi(0, "DropBarKindSwitchStatement", { fg = "#c3cfff" })
hi(0, "DropBarKindType", { fg = "#c3cfff" })
hi(0, "DropBarKindTypeParameter", { fg = "#c3cfff" })
hi(0, "DropBarKindUnit", { fg = "#c3cfff" })
hi(0, "DropBarKindValue", { fg = "#c3cfff" })
hi(0, "DropBarKindVariable", { fg = "#c3cfff" })
hi(0, "DropBarKindWhileStatement", { fg = "#c3cfff" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#2a315b" })
hi(0, "Error", { fg = "#f9747a" })
hi(0, "ErrorMsg", { bold = true, fg = "#f9747a" })
hi(0, "FinderBorder", { fg = "#83a8ff" })
hi(0, "FinderCode", { fg = "#6b76b0" })
hi(0, "FinderCount", { fg = "#fd9761" })
hi(0, "FinderIcon", { fg = "#efc672" })
hi(0, "FinderLines", { fg = "#7dd6e5" })
hi(0, "FinderNormal", {})
hi(0, "FinderPreview", { bg = "#506373", fg = "#c3cfff" })
hi(0, "FinderPreviewBorder", { fg = "#83a8ff" })
hi(0, "FinderSelection", { fg = "#99d76b" })
hi(0, "FinderSpinner", { fg = "#d196f6" })
hi(0, "FinderSpinnerTitle", { fg = "#d196f6" })
hi(0, "FinderStart", { fg = "#83a8ff" })
hi(0, "FinderType", { fg = "#b8b9ff" })
hi(0, "Float", { fg = "#fd9761" })
hi(0, "FloatBorder", { fg = "#83a8ff" })
hi(0, "FloatTitle", { fg = "#a0ace0" })
hi(0, "FlutterToolsOutlineIndentGuides", { fg = "#6b76b0" })
hi(0, "FoldColumn", { fg = "#6b76b0" })
hi(0, "Folded", { fg = "#83a8ff" })
hi(0, "Function", { fg = "#83a8ff" })
hi(0, "GitSignsAdd", { fg = "#99d76b" })
hi(0, "GitSignsAddInline", { bold = true, fg = "#99d76b" })
hi(0, "GitSignsAddLn", { bg = "#455052" })
hi(0, "GitSignsAddLnInline", { bold = true, fg = "#99d76b" })
hi(0, "GitSignsAddNr", { fg = "#99d76b" })
hi(0, "GitSignsAddPreview", { fg = "#79aa60" })
hi(0, "GitSignsChange", { fg = "#efc672" })
hi(0, "GitSignsChangeInline", { bold = true, fg = "#efc672" })
hi(0, "GitSignsChangeLn", { bg = "#363c52" })
hi(0, "GitSignsChangeLnInline", { bold = true, fg = "#efc672" })
hi(0, "GitSignsChangeNr", { fg = "#efc672" })
hi(0, "GitSignsChangedelete", { fg = "#efc672" })
hi(0, "GitSignsChangedeleteLn", { bg = "#363c52" })
hi(0, "GitSignsChangedeleteNr", { fg = "#efc672" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#6b76b0" })
hi(0, "GitSignsDelete", { fg = "#f9747a" })
hi(0, "GitSignsDeleteInline", { bold = true, fg = "#f9747a" })
hi(0, "GitSignsDeleteLnInline", { bold = true, fg = "#f9747a" })
hi(0, "GitSignsDeleteNr", { fg = "#f9747a" })
hi(0, "GitSignsDeletePreview", { fg = "#c95b6a" })
hi(0, "GitSignsDeleteVirtLn", { fg = "#f9747a" })
hi(0, "GitSignsDeleteVirtLnInLine", { bold = true, fg = "#f9747a" })
hi(0, "GitSignsStagedAdd", { fg = "#4c6b34" })
hi(0, "GitSignsStagedAddLn", { bg = "#455052" })
hi(0, "GitSignsStagedAddNr", { fg = "#4c6b34" })
hi(0, "GitSignsStagedChange", { fg = "#786338" })
hi(0, "GitSignsStagedChangeLn", { bg = "#363c52" })
hi(0, "GitSignsStagedChangeNr", { fg = "#786338" })
hi(0, "GitSignsStagedChangedelete", { fg = "#786338" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#363c52" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#786338" })
hi(0, "GitSignsStagedDelete", { fg = "#81363a" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#81363a" })
hi(0, "GitSignsStagedTopdelete", { fg = "#81363a" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#81363a" })
hi(0, "GitSignsTopdelete", { fg = "#f9747a" })
hi(0, "GitSignsTopdeleteNr", { fg = "#f9747a" })
hi(0, "GitSignsUntracked", { fg = "#99d76b" })
hi(0, "GitSignsUntrackedLn", { bg = "#455052" })
hi(0, "GitSignsUntrackedNr", { fg = "#99d76b" })
hi(0, "GitSignsVirtLnum", { fg = "#f9747a" })
hi(0, "GlyphPalette1", { fg = "#f9747a" })
hi(0, "GlyphPalette2", { fg = "#63cdc0" })
hi(0, "GlyphPalette3", { fg = "#efc672" })
hi(0, "GlyphPalette4", { fg = "#83a8ff" })
hi(0, "GlyphPalette6", { fg = "#63cdc0" })
hi(0, "GlyphPalette7", { fg = "#c3cfff" })
hi(0, "GlyphPalette9", { fg = "#f9747a" })
hi(0, "HoverBorder", { fg = "#83a8ff" })
hi(0, "HoverNormal", {})
hi(0, "Identifier", { fg = "#fab8b9" })
hi(0, "IncSearch", { bg = "#8fc1cc", fg = "#25294e" })
hi(0, "Include", { fg = "#d196f6" })
hi(0, "IndentBlanklineChar", { fg = "#3a4173" })
hi(0, "IndentBlanklineContextChar", { fg = "#c3cfff" })
hi(0, "IndentBlanklineContextStart", { sp = "#c6d0f5", underline = true })
hi(0, "Keyword", { fg = "#d196f6" })
hi(0, "Label", { fg = "#6bc4ea" })
hi(0, "LineNr", { fg = "#47538d" })
hi(0, "LspCodeLens", { fg = "#6b76b0" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#f9747a" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#63cdc0" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#7dd6e5" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#efc672" })
hi(0, "LspDiagnosticsError", { fg = "#f9747a" })
hi(0, "LspDiagnosticsHint", { fg = "#63cdc0" })
hi(0, "LspDiagnosticsInformation", { fg = "#7dd6e5" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#e78284", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#99d1db", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#e5c890", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#f9747a" })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#63cdc0" })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#7dd6e5" })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#efc672" })
hi(0, "LspDiagnosticsWarning", { fg = "#efc672" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInfoFiletype", { fg = "#efc672" })
hi(0, "LspInfoList", { fg = "#83a8ff" })
hi(0, "LspInfoTip", { fg = "#6b76b0" })
hi(0, "LspInfoTitle", { bold = true, fg = "#83a8ff" })
hi(0, "LspInlayHint", { fg = "#6b76b0" })
hi(0, "LspReferenceRead", { bg = "#51576d" })
hi(0, "LspReferenceText", { bg = "#51576d" })
hi(0, "LspReferenceWrite", { bg = "#51576d" })
hi(0, "LspSignatureActiveParameter", { fg = "#fd9761" })
hi(0, "Macro", { fg = "#d196f6" })
hi(0, "MatchParen", { bg = "#51576d", bold = true, fg = "#fd9761" })
hi(0, "ModeMsg", { bold = true, fg = "#c3cfff" })
hi(0, "MoreMsg", { fg = "#83a8ff" })
hi(0, "MsgSeparator", {})
hi(0, "MyCopilotIcon", { fg = "#ffa509" })
hi(0, "NonText", { fg = "#6b76b0" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#c3cfff" })
hi(0, "NormalSB", { bg = "#232634", fg = "#c3cfff" })
hi(0, "NullLsInfoBorder", {})
hi(0, "NullLsInfoHeader", { fg = "#6bc4ea" })
hi(0, "NullLsInfoSources", { bold = true, fg = "#83a8ff" })
hi(0, "NullLsInfoTitle", { fg = "#efc672" })
hi(0, "Number", { fg = "#fd9761" })
hi(0, "NvimTreeBookmark", { fg = "#63cdc0" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#83a8ff" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#63cdc0" })
hi(0, "NvimTreeFolderIcon", { fg = "#83a8ff" })
hi(0, "NvimTreeFolderName", { fg = "#83a8ff" })
hi(0, "NvimTreeGitDeleted", { fg = "#f9747a" })
hi(0, "NvimTreeGitDirty", { fg = "#efc672" })
hi(0, "NvimTreeGitMerge", { fg = "#fd9761" })
hi(0, "NvimTreeGitNew", { fg = "#83a8ff" })
hi(0, "NvimTreeGitRenamed", { fg = "#ffb0eb" })
hi(0, "NvimTreeGitStaged", { fg = "#63cdc0" })
hi(0, "NvimTreeImageFile", { fg = "#c3cfff" })
hi(0, "NvimTreeIndentMarker", { fg = "#6b76b0" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#ffb0eb" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeNormal", { fg = "#c3cfff" })
hi(0, "NvimTreeOpenedFile", { fg = "#ffb0eb" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#83a8ff" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b8b9ff" })
hi(0, "NvimTreeSpecialFile", { fg = "#fab8b9" })
hi(0, "NvimTreeStatuslineNc", { bg = "#292c3c", fg = "#25294e" })
hi(0, "NvimTreeSymlink", { fg = "#ffb0eb" })
hi(0, "NvimTreeWinSeparator", { fg = "#47538d" })
hi(0, "NvimTreeWindowPicker", { bg = "#4493c8", bold = true, fg = "#ededed" })
hi(0, "Operator", { fg = "#7dd6e5" })
hi(0, "OutlineIndent", { fg = "#8762b9" })
hi(0, "OutlinePreviewBorder", {})
hi(0, "OutlinePreviewNormal", { fg = "#83a8ff" })
hi(0, "OutlineWinSeparator", { fg = "#47538d" })
hi(0, "Pmenu", { fg = "#8d9ad0" })
hi(0, "PmenuSbar", { bg = "#51576d" })
hi(0, "PmenuSel", { bg = "#51576d", bold = true, fg = "#c3cfff" })
hi(0, "PmenuThumb", { bg = "#737994" })
hi(0, "PreProc", { fg = "#ffb0eb" })
hi(0, "Question", { fg = "#83a8ff" })
hi(0, "QuickFixLine", { bg = "#51576d", bold = true })
hi(0, "RenameBorder", { fg = "#83a8ff" })
hi(0, "RenameMatch", { bg = "#506373", fg = "#c3cfff" })
hi(0, "RenameNormal", { fg = "#d196f6" })
hi(0, "Repeat", { fg = "#d196f6" })
hi(0, "SagaBeacon", { bg = "#c43963" })
hi(0, "SagaBorder", { fg = "#83a8ff" })
hi(0, "SagaCollapse", { fg = "#38507f" })
hi(0, "SagaCount", { fg = "#6b76b0" })
hi(0, "SagaExpand", { fg = "#38507f" })
hi(0, "SagaLightBulb", { fg = "#63cdc0" })
hi(0, "SagaShadow", { bg = "#000000", blend = 80 })
hi(0, "SagaWinbarArray", { fg = "#efc672" })
hi(0, "SagaWinbarBoolean", { fg = "#fd9761" })
hi(0, "SagaWinbarClass", { fg = "#d196f6" })
hi(0, "SagaWinbarConstant", { fg = "#fd9761" })
hi(0, "SagaWinbarConstructor", { fg = "#6bc4ea" })
hi(0, "SagaWinbarEnum", { fg = "#fd9761" })
hi(0, "SagaWinbarEnumMember", { fg = "#fd9761" })
hi(0, "SagaWinbarEvent", { fg = "#fd9761" })
hi(0, "SagaWinbarField", { fg = "#b8b9ff" })
hi(0, "SagaWinbarFile", { fg = "#ffb0eb" })
hi(0, "SagaWinbarFileIcon", { fg = "#01589d" })
hi(0, "SagaWinbarFilename", { fg = "#bac3a1" })
hi(0, "SagaWinbarFolder", { bold = true, fg = "#83a8ff" })
hi(0, "SagaWinbarFolderName", { fg = "#bac3a1" })
hi(0, "SagaWinbarFunction", { fg = "#83a8ff" })
hi(0, "SagaWinbarInterface", { fg = "#efc672" })
hi(0, "SagaWinbarKey", { fg = "#fd9761" })
hi(0, "SagaWinbarMacro", { fg = "#d196f6" })
hi(0, "SagaWinbarMethod", { fg = "#83a8ff" })
hi(0, "SagaWinbarModule", { fg = "#d196f6" })
hi(0, "SagaWinbarNamespace", { fg = "#d196f6" })
hi(0, "SagaWinbarNull", { fg = "#fd9761" })
hi(0, "SagaWinbarNumber", { fg = "#fd9761" })
hi(0, "SagaWinbarObject", { fg = "#efc672" })
hi(0, "SagaWinbarOperator", { fg = "#7dd6e5" })
hi(0, "SagaWinbarPackage", { fg = "#6bc4ea" })
hi(0, "SagaWinbarParameter", { fg = "#fa8f94" })
hi(0, "SagaWinbarProperty", { fg = "#b8b9ff" })
hi(0, "SagaWinbarSep", { fg = "#7dd6e5" })
hi(0, "SagaWinbarSnippet", { fg = "#c3cfff" })
hi(0, "SagaWinbarStaticMethod", { fg = "#83a8ff" })
hi(0, "SagaWinbarString", { fg = "#99d76b" })
hi(0, "SagaWinbarStruct", { fg = "#efc672" })
hi(0, "SagaWinbarText", { fg = "#99d76b" })
hi(0, "SagaWinbarTypeAlias", { fg = "#efc672" })
hi(0, "SagaWinbarTypeParameter", { fg = "#fa8f94" })
hi(0, "SagaWinbarUnit", { fg = "#fd9761" })
hi(0, "SagaWinbarValue", { fg = "#c3cfff" })
hi(0, "SagaWinbarVariable", { fg = "#c3cfff" })
hi(0, "Search", { bg = "#506373", fg = "#c3cfff" })
hi(0, "SignColumn", { fg = "#47538d" })
hi(0, "SignColumnSB", { bg = "#232634", fg = "#47538d" })
hi(0, "Special", { fg = "#ffb0eb" })
hi(0, "SpecialKey", { fg = "#c3cfff" })
hi(0, "SpellBad", { sp = "#e78284", undercurl = true })
hi(0, "SpellCap", { sp = "#e5c890", undercurl = true })
hi(0, "SpellLocal", { sp = "#8caaee", undercurl = true })
hi(0, "SpellRare", { sp = "#a6d189", undercurl = true })
hi(0, "Statement", { fg = "#d196f6" })
hi(0, "StatusLine", { fg = "#c3cfff" })
hi(0, "StatusLineNC", { fg = "#47538d" })
hi(0, "StorageClass", { fg = "#efc672" })
hi(0, "String", { fg = "#99d76b" })
hi(0, "Structure", { fg = "#efc672" })
hi(0, "Substitute", { bg = "#51576d", fg = "#ffb0eb" })
hi(0, "TSRainbowBlue", { fg = "#83a8ff" })
hi(0, "TSRainbowCyan", { fg = "#63cdc0" })
hi(0, "TSRainbowGreen", { fg = "#99d76b" })
hi(0, "TSRainbowOrange", { fg = "#fd9761" })
hi(0, "TSRainbowRed", { fg = "#f9747a" })
hi(0, "TSRainbowViolet", { fg = "#d196f6" })
hi(0, "TSRainbowYellow", { fg = "#efc672" })
hi(0, "TabLine", { bg = "#292c3c", fg = "#47538d" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#51576d", fg = "#99d76b" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#83a8ff" })
hi(0, "TelescopeMultiIcon", { fg = "#fab8b9" })
hi(0, "TelescopeMultiSelection", { fg = "#efc672" })
hi(0, "TelescopeNormal", {})
hi(0, "TelescopePreviewBlock", { fg = "#fd9761" })
hi(0, "TelescopePreviewBorder", { fg = "#83a8ff" })
hi(0, "TelescopePreviewCharDev", { fg = "#fd9761" })
hi(0, "TelescopePreviewDate", { fg = "#83a8ff" })
hi(0, "TelescopePreviewDirectory", { fg = "#83a8ff" })
hi(0, "TelescopePreviewExecute", { fg = "#99d76b" })
hi(0, "TelescopePreviewGroup", { fg = "#fd9761" })
hi(0, "TelescopePreviewHyphen", { fg = "#6b76b0" })
hi(0, "TelescopePreviewLine", { bg = "#51576d", bold = true })
hi(0, "TelescopePreviewLink", { fg = "#ffb0eb" })
hi(0, "TelescopePreviewMatch", { bg = "#506373", fg = "#c3cfff" })
hi(0, "TelescopePreviewMessage", {})
hi(0, "TelescopePreviewMessageFillchar", {})
hi(0, "TelescopePreviewNormal", {})
hi(0, "TelescopePreviewPipe", { fg = "#fd9761" })
hi(0, "TelescopePreviewRead", { fg = "#fd9761" })
hi(0, "TelescopePreviewSize", { fg = "#99d76b" })
hi(0, "TelescopePreviewSocket", { fg = "#d196f6" })
hi(0, "TelescopePreviewSticky", { fg = "#d196f6" })
hi(0, "TelescopePreviewTitle", { fg = "#83a8ff" })
hi(0, "TelescopePreviewUser", { fg = "#fd9761" })
hi(0, "TelescopePreviewWrite", { fg = "#d196f6" })
hi(0, "TelescopePromptBorder", { fg = "#83a8ff" })
hi(0, "TelescopePromptCounter", { fg = "#6b76b0" })
hi(0, "TelescopePromptNormal", {})
hi(0, "TelescopePromptPrefix", { fg = "#fab8b9" })
hi(0, "TelescopePromptTitle", { fg = "#83a8ff" })
hi(0, "TelescopeResultsBorder", { fg = "#83a8ff" })
hi(0, "TelescopeResultsClass", { fg = "#83a8ff" })
hi(0, "TelescopeResultsComment", { fg = "#6b76b0" })
hi(0, "TelescopeResultsConstant", { fg = "#fd9761" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#455052" })
hi(0, "TelescopeResultsDiffChange", { bg = "#363c52" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#514251" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#6b76b0" })
hi(0, "TelescopeResultsField", { fg = "#83a8ff" })
hi(0, "TelescopeResultsFunction", { fg = "#83a8ff" })
hi(0, "TelescopeResultsIdentifier", { fg = "#fab8b9" })
hi(0, "TelescopeResultsLineNr", { fg = "#47538d" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", {})
hi(0, "TelescopeResultsNumber", { fg = "#fd9761" })
hi(0, "TelescopeResultsOperator", { fg = "#7dd6e5" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#ffb0eb" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#83a8ff" })
hi(0, "TelescopeResultsVariable", { fg = "#ffb0eb" })
hi(0, "TelescopeSelection", { bold = true, fg = "#fab8b9" })
hi(0, "TelescopeSelectionCaret", { fg = "#fab8b9" })
hi(0, "TelescopeTitle", { fg = "#83a8ff" })
hi(0, "TerminalBorder", { fg = "#83a8ff" })
hi(0, "TerminalNormal", {})
hi(0, "Title", { bold = true, fg = "#83a8ff" })
hi(0, "TitleIcon", { fg = "#d196f6" })
hi(0, "TitleString", { bold = true, fg = "#83a8ff" })
hi(0, "Todo", { bg = "#e5c890", bold = true, fg = "#2a315b" })
hi(0, "Type", { fg = "#efc672" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#47538d" })
hi(0, "Visual", { bg = "#51576d", bold = true })
hi(0, "VisualNOS", { bg = "#51576d", bold = true })
hi(0, "WarningMsg", { fg = "#efc672" })
hi(0, "Whitespace", { fg = "#47538d" })
hi(0, "WildMenu", { bg = "#737994" })
hi(0, "WinBar", { fg = "#fbd2c9" })
hi(0, "debugBreakpoint", { bg = "#303446", fg = "#6b76b0" })
hi(0, "diffAdded", { fg = "#99d76b" })
hi(0, "diffChanged", { fg = "#83a8ff" })
hi(0, "diffFile", { fg = "#83a8ff" })
hi(0, "diffIndexLine", { fg = "#63cdc0" })
hi(0, "diffLine", { fg = "#6b76b0" })
hi(0, "diffNewFile", { fg = "#fd9761" })
hi(0, "diffOldFile", { fg = "#efc672" })
hi(0, "diffRemoved", { fg = "#f9747a" })
hi(0, "healthError", { fg = "#f9747a" })
hi(0, "healthSuccess", { fg = "#63cdc0" })
hi(0, "healthWarning", { fg = "#efc672" })
hi(0, "htmlH1", { bold = true, fg = "#ffb0eb" })
hi(0, "htmlH2", { bold = true, fg = "#83a8ff" })
hi(0, "illuminatedCurWord", { bg = "#51576d" })
hi(0, "illuminatedWord", { bg = "#51576d" })
hi(0, "lCursor", { bg = "#c6d0f5", fg = "#2a315b" })
hi(0, "lualine_a_command", { bg = "#ef9f76", bold = true, fg = "#2a315b" })
hi(0, "lualine_a_inactive", { fg = "#83a8ff" })
hi(0, "lualine_a_insert", { bg = "#a6d189", bold = true, fg = "#2a315b" })
hi(0, "lualine_a_normal", { bg = "#8caaee", bold = true, fg = "#25294e" })
hi(0, "lualine_a_replace", { bg = "#e78284", bold = true, fg = "#2a315b" })
hi(0, "lualine_a_terminal", { bg = "#a6d189", bold = true, fg = "#2a315b" })
hi(0, "lualine_a_visual", { bg = "#ca9ee6", bold = true, fg = "#2a315b" })
hi(0, "lualine_b_command", { bg = "#51576d", fg = "#fd9761" })
hi(0, "lualine_b_inactive", { bold = true, fg = "#47538d" })
hi(0, "lualine_b_insert", { bg = "#51576d", fg = "#63cdc0" })
hi(0, "lualine_b_normal", { bg = "#51576d", fg = "#83a8ff" })
hi(0, "lualine_b_replace", { bg = "#51576d", fg = "#f9747a" })
hi(0, "lualine_b_terminal", { bg = "#51576d", fg = "#63cdc0" })
hi(0, "lualine_b_visual", { bg = "#51576d", fg = "#d196f6" })
hi(0, "lualine_c_inactive", { fg = "#6b76b0" })
hi(0, "lualine_c_normal", { fg = "#c3cfff" })
hi(0, "lualine_x_filetype_DevIconDart_command", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_inactive", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_insert", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_normal", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_replace", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_terminal", { fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_visual", { fg = "#01589d" })
hi(0, "markdownCode", { fg = "#fab8b9" })
hi(0, "markdownCodeBlock", { fg = "#fab8b9" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#fd9761" })
hi(0, "markdownLinkText", { fg = "#83a8ff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#303446", fg = "#c3cfff" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#fab8b9" })
hi(0, "mkdCodeStart", { bold = true, fg = "#fab8b9" })
hi(0, "qfFileName", { fg = "#83a8ff" })
hi(0, "qfLineNr", { fg = "#efc672" })
hi(0, "rainbow1", { fg = "#f9747a" })
hi(0, "rainbow2", { fg = "#fd9761" })
hi(0, "rainbow3", { fg = "#efc672" })
hi(0, "rainbow4", { fg = "#99d76b" })
hi(0, "rainbow5", { fg = "#6bc4ea" })
hi(0, "rainbow6", { fg = "#b8b9ff" })
hi(0, "rainbowcol1", { fg = "#f9747a" })
hi(0, "rainbowcol2", { fg = "#63cdc0" })
hi(0, "rainbowcol3", { fg = "#efc672" })
hi(0, "rainbowcol4", { fg = "#83a8ff" })
hi(0, "rainbowcol5", { fg = "#ffb0eb" })
hi(0, "rainbowcol6", { fg = "#fab8b9" })
hi(0, "rainbowcol7", { fg = "#99d76b" })

-- No terminal colors defined
