-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kanagawa"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@constructor", { fg = "#73b6d1" })
hi(0, "@constructor.lua", { fg = "#987bc4" })
hi(0, "@exception", { bold = true, fg = "#ff555d" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#c5a261" })
hi(0, "@keyword.return", { fg = "#ff555d", italic = true })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#789be2" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@exception" })
hi(0, "@lsp.typemod.operator.injected", { link = "Operator" })
hi(0, "@lsp.typemod.string.injected", { link = "String" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@parameter", { fg = "#b8b3d8" })
hi(0, "@punctuation.bracket", { fg = "#97abd3" })
hi(0, "@punctuation.delimiter", { fg = "#97abd3" })
hi(0, "@punctuation.special", { fg = "#73b6d1" })
hi(0, "@string.escape", { bold = true, fg = "#c5a261" })
hi(0, "@string.regex", { fg = "#c5a261" })
hi(0, "@symbol", { fg = "#ebc275" })
hi(0, "@tag.attribute", { fg = "#ebc275" })
hi(0, "@tag.delimiter", { fg = "#97abd3" })
hi(0, "@text.danger", { bg = "#e82424", bold = true, fg = "#dfd7ac" })
hi(0, "@text.diff.add", { fg = "#709760" })
hi(0, "@text.diff.delete", { fg = "#cc323b" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Keyword" })
hi(0, "@text.environment.name", { link = "String" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Constant" })
hi(0, "@text.note", { bg = "#6a9589", bold = true, fg = "#1e324f" })
hi(0, "@text.quote", { link = "@parameter" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Function" })
hi(0, "@text.warning", { bg = "#ff9e3b", bold = true, fg = "#1e324f" })
hi(0, "@variable", { fg = "#dfd7ac" })
hi(0, "@variable.builtin", { fg = "#ee5e71", italic = true })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#ff9e5f" })
hi(0, "BufferAlternate", {})
hi(0, "BufferAlternateADDED", {})
hi(0, "BufferAlternateCHANGED", {})
hi(0, "BufferAlternateDELETED", {})
hi(0, "BufferAlternateERROR", {})
hi(0, "BufferAlternateHINT", {})
hi(0, "BufferAlternateINFO", {})
hi(0, "BufferAlternateIcon", {})
hi(0, "BufferAlternateIndex", {})
hi(0, "BufferAlternateMod", {})
hi(0, "BufferAlternateNumber", {})
hi(0, "BufferAlternateSign", {})
hi(0, "BufferAlternateSignRight", {})
hi(0, "BufferAlternateTarget", {})
hi(0, "BufferAlternateWARN", {})
hi(0, "BufferCurrent", { bg = "#2a2a37", ctermfg = 255, fg = "#cbc086" })
hi(0, "BufferCurrentADDED", { bg = "#2a2a37", ctermfg = 82, fg = "#709760" })
hi(0, "BufferCurrentCHANGED", { bg = "#2a2a37", ctermfg = 75, fg = "#e2a351" })
hi(0, "BufferCurrentDELETED", { bg = "#2a2a37", ctermfg = 124, fg = "#cc323b" })
hi(0, "BufferCurrentERROR", { bg = "#2a2a37", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferCurrentHINT", { bg = "#2a2a37", ctermfg = 168, fg = "#619789" })
hi(0, "BufferCurrentINFO", { bg = "#2a2a37", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferCurrentIcon", { bg = "#2a2a37", ctermfg = 255, fg = "#cbc086" })
hi(0, "BufferCurrentIndex", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferCurrentMod", { bg = "#2a2a37", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferCurrentNumber", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferCurrentSign", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferCurrentSignRight", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferCurrentTarget", { bg = "#2a2a37", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferCurrentWARN", { bg = "#2a2a37", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultAlternateIcon", {})
hi(0, "BufferDefaultAlternateNumber", {})
hi(0, "BufferDefaultAlternateSignRight", {})
hi(0, "BufferDefaultCurrent", { bg = "#2a2a37", ctermfg = 255, fg = "#cbc086" })
hi(0, "BufferDefaultCurrentADDED", { bg = "#2a2a37", ctermfg = 82, fg = "#709760" })
hi(0, "BufferDefaultCurrentCHANGED", { bg = "#2a2a37", ctermfg = 75, fg = "#e2a351" })
hi(0, "BufferDefaultCurrentDELETED", { bg = "#2a2a37", ctermfg = 124, fg = "#cc323b" })
hi(0, "BufferDefaultCurrentERROR", { bg = "#2a2a37", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferDefaultCurrentHINT", { bg = "#2a2a37", ctermfg = 168, fg = "#619789" })
hi(0, "BufferDefaultCurrentINFO", { bg = "#2a2a37", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferDefaultCurrentIcon", { bg = "#2a2a37", ctermfg = 255, fg = "#cbc086" })
hi(0, "BufferDefaultCurrentIndex", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferDefaultCurrentMod", { bg = "#2a2a37", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferDefaultCurrentNumber", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferDefaultCurrentSign", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferDefaultCurrentSignRight", { bg = "#2a2a37", ctermfg = 75, fg = "#73b6d1" })
hi(0, "BufferDefaultCurrentTarget", { bg = "#2a2a37", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultCurrentWARN", { bg = "#2a2a37", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultInactive", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultInactiveADDED", { bg = "#16161d", ctermfg = 82, fg = "#709760" })
hi(0, "BufferDefaultInactiveCHANGED", { bg = "#16161d", ctermfg = 75, fg = "#e2a351" })
hi(0, "BufferDefaultInactiveDELETED", { bg = "#16161d", ctermfg = 124, fg = "#cc323b" })
hi(0, "BufferDefaultInactiveERROR", { bg = "#16161d", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferDefaultInactiveHINT", { bg = "#16161d", ctermfg = 168, fg = "#619789" })
hi(0, "BufferDefaultInactiveINFO", { bg = "#16161d", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferDefaultInactiveIcon", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultInactiveIndex", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferDefaultInactiveMod", { bg = "#16161d", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferDefaultInactiveNumber", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferDefaultInactiveSign", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferDefaultInactiveSignRight", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferDefaultInactiveTarget", { bg = "#16161d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultInactiveWARN", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultOffset", { bg = "#1f1f28", ctermfg = 102, fg = "#cbc086" })
hi(0, "BufferDefaultTabpageFill", { bg = "#1f1f28", ctermfg = 102, fg = "#cbc086" })
hi(0, "BufferDefaultTabpages", { bg = "#1f1f28", bold = true, ctermfg = 75, fg = "#dc7699" })
hi(0, "BufferDefaultTabpagesSep", { bg = "#1f1f28", bold = true, ctermfg = 255, fg = "#97abd3" })
hi(0, "BufferDefaultVisible", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleADDED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultVisibleCHANGED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultVisibleDELETED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferDefaultVisibleERROR", { bg = "#16161d", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferDefaultVisibleHINT", { bg = "#16161d", ctermfg = 168, fg = "#619789" })
hi(0, "BufferDefaultVisibleINFO", { bg = "#16161d", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferDefaultVisibleIcon", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleIndex", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleMod", { bg = "#16161d", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferDefaultVisibleNumber", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleSign", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleSignRight", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferDefaultVisibleTarget", { bg = "#16161d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultVisibleWARN", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferInactive", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferInactiveADDED", { bg = "#16161d", ctermfg = 82, fg = "#709760" })
hi(0, "BufferInactiveCHANGED", { bg = "#16161d", ctermfg = 75, fg = "#e2a351" })
hi(0, "BufferInactiveDELETED", { bg = "#16161d", ctermfg = 124, fg = "#cc323b" })
hi(0, "BufferInactiveERROR", { bg = "#16161d", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferInactiveHINT", { bg = "#16161d", ctermfg = 168, fg = "#619789" })
hi(0, "BufferInactiveINFO", { bg = "#16161d", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferInactiveIcon", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferInactiveIndex", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferInactiveMod", { bg = "#16161d", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferInactiveNumber", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferInactiveSign", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferInactiveSignRight", { bg = "#16161d", ctermfg = 240, fg = "#53517b" })
hi(0, "BufferInactiveTarget", { bg = "#16161d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferInactiveWARN", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferOffset", { bg = "#1f1f28", ctermfg = 102, fg = "#cbc086" })
hi(0, "BufferScrollArrow", { bg = "#1f1f28", bold = true, ctermfg = 255, fg = "#97abd3" })
hi(0, "BufferTabpageFill", { bg = "#1f1f28", ctermfg = 102, fg = "#cbc086" })
hi(0, "BufferTabpages", { bg = "#1f1f28", bold = true, ctermfg = 75, fg = "#dc7699" })
hi(0, "BufferTabpagesSep", { bg = "#1f1f28", bold = true, ctermfg = 255, fg = "#97abd3" })
hi(0, "BufferVisible", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleADDED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferVisibleCHANGED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferVisibleDELETED", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "BufferVisibleERROR", { bg = "#16161d", ctermfg = 124, fg = "#ef0015" })
hi(0, "BufferVisibleHINT", { bg = "#16161d", ctermfg = 168, fg = "#619789" })
hi(0, "BufferVisibleINFO", { bg = "#16161d", ctermfg = 217, fg = "#5d869a" })
hi(0, "BufferVisibleIcon", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleIndex", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleMod", { bg = "#16161d", ctermfg = 178, fg = "#ff9e38" })
hi(0, "BufferVisibleNumber", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleSign", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleSignRight", { bg = "#16161d", ctermfg = 255, fg = "#9587b5" })
hi(0, "BufferVisibleTarget", { bg = "#16161d", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferVisibleWARN", { bg = "#16161d", ctermfg = 208, fg = "#ff9e38" })
hi(0, "Character", { link = "String" })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#223249", fg = "#264f6c" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { bg = "#2d4f67" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpItemAbbr", { fg = "#dfd7ac" })
hi(0, "CmpItemAbbrDefault", { fg = "#dfd7ac" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#737162", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#737162" })
hi(0, "CmpItemAbbrMatch", { fg = "#789be2" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#dfd7ac" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#dfd7ac" })
hi(0, "CmpItemKind", { fg = "#73b6d1" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#73b6d1" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { ctermfg = 6, fg = "#01ff01" })
hi(0, "CmpItemKindDefault", { fg = "#73b6d1" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#73b6d1" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "@keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@include" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Type" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#73b6d1" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#dfd7ac" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#73b6d1" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#cbc086" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#737162" })
hi(0, "CmpItemMenuDefault", { fg = "#dfd7ac" })
hi(0, "ColorColumn", { bg = "#2a2a37" })
hi(0, "Comment", { fg = "#737162", italic = true })
hi(0, "Conceal", { bold = true, fg = "#9587b5" })
hi(0, "Constant", { fg = "#ff9e5f" })
hi(0, "CurSearch", { bg = "#2d4f67", bold = true, fg = "#dfd7ac" })
hi(0, "Cursor", { bg = "#dcd7ba", fg = "#1e1e2e" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#363646" })
hi(0, "CursorLineNr", { bold = true, fg = "#ff9e38" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#ebc275" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#5d869a" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#53517b" })
hi(0, "DapUIFloatBorder", { fg = "#53517b" })
hi(0, "DapUILineNumber", { fg = "#73b6d1" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#73b6d1" })
hi(0, "DapUINormalNC", {})
hi(0, "DapUIPlayPause", { fg = "#94bd5e" })
hi(0, "DapUIPlayPauseNC", { fg = "#94bd5e" })
hi(0, "DapUIRestart", { fg = "#94bd5e" })
hi(0, "DapUIRestartNC", { fg = "#94bd5e" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#ee5e71" })
hi(0, "DapUIStepBack", { fg = "#73b6d1" })
hi(0, "DapUIStepBackNC", { fg = "#73b6d1" })
hi(0, "DapUIStepInto", { fg = "#73b6d1" })
hi(0, "DapUIStepIntoNC", { fg = "#73b6d1" })
hi(0, "DapUIStepOut", { fg = "#73b6d1" })
hi(0, "DapUIStepOutNC", { fg = "#73b6d1" })
hi(0, "DapUIStepOver", { fg = "#73b6d1" })
hi(0, "DapUIStepOverNC", { fg = "#73b6d1" })
hi(0, "DapUIStop", { fg = "#ef0015" })
hi(0, "DapUIStopNC", { fg = "#ef0015" })
hi(0, "DapUIStoppedThread", { fg = "#73b6d1" })
hi(0, "DapUIThread", { fg = "#ebc275" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#737162" })
hi(0, "DapUIUnavailableNC", { fg = "#737162" })
hi(0, "DapUIWatchesEmpty", { fg = "#ef0015" })
hi(0, "DapUIWatchesError", { fg = "#ef0015" })
hi(0, "DapUIWatchesValue", { fg = "#ebc275" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#ebc275" })
hi(0, "DashboardDesc", { fg = "#ebc275" })
hi(0, "DashboardFooter", { fg = "#737162" })
hi(0, "DashboardHeader", { fg = "#cc323b" })
hi(0, "DashboardIcon", { fg = "#9587b5" })
hi(0, "DashboardKey", { fg = "#73b6d1" })
hi(0, "DashboardShortCut", { fg = "#73b6d1" })
hi(0, "Delimiter", { fg = "#97abd3" })
hi(0, "DiagnosticError", { fg = "#ef0015" })
hi(0, "DiagnosticHint", { fg = "#619789" })
hi(0, "DiagnosticInfo", { fg = "#5d869a" })
hi(0, "DiagnosticOk", { fg = "#94bd5e" })
hi(0, "DiagnosticSignError", { fg = "#ef0015" })
hi(0, "DiagnosticSignHint", { fg = "#619789" })
hi(0, "DiagnosticSignInfo", { fg = "#5d869a" })
hi(0, "DiagnosticSignWarn", { fg = "#ff9e38" })
hi(0, "DiagnosticUnderlineError", { sp = "#e82424", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6a9589", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#658594", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ff9e3b", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#ff9e38" })
hi(0, "DiffAdd", { bg = "#2b3328" })
hi(0, "DiffChange", { bg = "#252535" })
hi(0, "DiffDelete", { bg = "#43242b", fg = "#cc323b" })
hi(0, "DiffText", { bg = "#49443c" })
hi(0, "Directory", { fg = "#789be2" })
hi(0, "EndOfBuffer", { fg = "#1e1e2e" })
hi(0, "Error", { fg = "#ef0015" })
hi(0, "ErrorMsg", { fg = "#ef0015" })
hi(0, "Exception", { fg = "#ee5e71" })
hi(0, "FloatBorder", { bg = "#16161d", fg = "#53517b" })
hi(0, "FloatTitle", { bg = "#16161d", bold = true, fg = "#9587b5" })
hi(0, "FloatermBorder", { bg = "#1f1f28", fg = "#53517b" })
hi(0, "FoldColumn", { fg = "#53517b" })
hi(0, "Folded", { bg = "#2a2a37", fg = "#9587b5" })
hi(0, "Function", { fg = "#789be2" })
hi(0, "GitSignsAdd", { fg = "#709760" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#2b3328" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { fg = "#709760" })
hi(0, "GitSignsAddPreview", { bg = "#2b3328" })
hi(0, "GitSignsChange", { fg = "#e2a351" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#252535" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { fg = "#e2a351" })
hi(0, "GitSignsChangedelete", { fg = "#e2a351" })
hi(0, "GitSignsChangedeleteLn", { bg = "#252535" })
hi(0, "GitSignsChangedeleteNr", { fg = "#e2a351" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#53517b" })
hi(0, "GitSignsDelete", { fg = "#cc323b" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { fg = "#cc323b" })
hi(0, "GitSignsDeletePreview", { bg = "#43242b", fg = "#cc323b" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#43242b", fg = "#cc323b" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { fg = "#384b30" })
hi(0, "GitSignsStagedAddLn", { bg = "#2b3328" })
hi(0, "GitSignsStagedAddNr", { fg = "#384b30" })
hi(0, "GitSignsStagedChange", { fg = "#715128" })
hi(0, "GitSignsStagedChangeLn", { bg = "#252535" })
hi(0, "GitSignsStagedChangeNr", { fg = "#715128" })
hi(0, "GitSignsStagedChangedelete", { fg = "#715128" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#252535" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#715128" })
hi(0, "GitSignsStagedDelete", { fg = "#661a1d" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#661a1d" })
hi(0, "GitSignsStagedTopdelete", { fg = "#661a1d" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#661a1d" })
hi(0, "GitSignsTopdelete", { fg = "#cc323b" })
hi(0, "GitSignsTopdeleteNr", { fg = "#cc323b" })
hi(0, "GitSignsUntracked", { fg = "#709760" })
hi(0, "GitSignsUntrackedLn", { bg = "#2b3328" })
hi(0, "GitSignsUntrackedNr", { fg = "#709760" })
hi(0, "GitSignsVirtLnum", { bg = "#43242b", fg = "#cc323b" })
hi(0, "Identifier", { fg = "#ebc275" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IncSearch", { bg = "#ff9e3b", fg = "#1e324f" })
hi(0, "IndentBlanklineChar", { fg = "#53517b" })
hi(0, "IndentBlanklineContextChar", { fg = "#9587b5" })
hi(0, "IndentBlanklineContextStart", { sp = "#938aa9", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#53517b" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#53517b" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#987bc4", italic = true })
hi(0, "LazyProgressTodo", { fg = "#53517b" })
hi(0, "LineNr", { fg = "#53517b" })
hi(0, "LspCodeLens", { fg = "#737162" })
hi(0, "LspInfoBorder", { bold = true, fg = "#987bc4" })
hi(0, "LspInfoFiletype", { fg = "#70ab9f" })
hi(0, "LspInfoList", { fg = "#789be2" })
hi(0, "LspInfoTip", { fg = "#737162", italic = true })
hi(0, "LspInfoTitle", { bold = true, fg = "#789be2" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#49443c" })
hi(0, "LspReferenceWrite", { bg = "#49443c", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#ff9e38" })
hi(0, "MatchParen", { bold = true, fg = "#ff9e38" })
hi(0, "ModeMsg", { bold = true, fg = "#ff9e38" })
hi(0, "MoreMsg", { fg = "#5d869a" })
hi(0, "MsgArea", { fg = "#cbc086" })
hi(0, "MsgSeparator", { bg = "#16161d" })
hi(0, "MyCopilotIcon", { fg = "#ffa509" })
hi(0, "NeoTreeGitAdded", { fg = "#709760" })
hi(0, "NeoTreeGitConflict", { fg = "#ef0015" })
hi(0, "NeoTreeGitDeleted", { fg = "#cc323b" })
hi(0, "NeoTreeGitModified", { fg = "#e2a351" })
hi(0, "NeoTreeGitStaged", { fg = "#709760" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e2a351" })
hi(0, "NeoTreeGitUntracked", { fg = "#e2a351" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#ebc275" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitDiffAddHighlight", { bg = "#2b3328" })
hi(0, "NeogitDiffContextHighlight", { bg = "#252535" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#43242b" })
hi(0, "NeogitHunkHeader", { fg = "#789be2" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#252535", fg = "#ff9e5f" })
hi(0, "NonText", { fg = "#53517b" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyBackground", { bg = "#1f1f28" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "NullLsInfoBorder", {})
hi(0, "NullLsInfoHeader", { bold = true, fg = "#987bc4" })
hi(0, "NullLsInfoSources", { bold = true, fg = "#789be2" })
hi(0, "NullLsInfoTitle", { fg = "#70ab9f" })
hi(0, "Number", { fg = "#dc7699" })
hi(0, "NvimTreeBookmark", { fg = "#709760" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#94bd5e" })
hi(0, "NvimTreeFolderIcon", { fg = "#7994bf" })
hi(0, "NvimTreeGitDeleted", { fg = "#cc323b" })
hi(0, "NvimTreeGitDirty", { fg = "#e2a351" })
hi(0, "NvimTreeGitMerge", { fg = "#ebc275" })
hi(0, "NvimTreeGitNew", { fg = "#709760" })
hi(0, "NvimTreeGitRenamed", { fg = "#987bc4" })
hi(0, "NvimTreeGitStaged", { fg = "#709760" })
hi(0, "NvimTreeImageFile", { fg = "#ee5e71" })
hi(0, "NvimTreeIndentMarker", { fg = "#7994bf" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#987bc4" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeOpenedFile", { fg = "#73b6d1", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#ebc275" })
hi(0, "NvimTreeSpecialFile", { fg = "#73b6d1" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWinSeparator", { link = "WinSeparator" })
hi(0, "NvimTreeWindowPicker", { bg = "#1a1a22", bold = true, fg = "#73b6d1" })
hi(0, "Operator", { fg = "#c5a261" })
hi(0, "Pmenu", { bg = "#223249", fg = "#dfd7ac" })
hi(0, "PmenuSbar", { bg = "#223249" })
hi(0, "PmenuSel", { bg = "#2d4f67" })
hi(0, "PmenuThumb", { bg = "#2d4f67" })
hi(0, "PreProc", { fg = "#ee5e71" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#2a2a37" })
hi(0, "Search", { bg = "#2d4f67", fg = "#dfd7ac" })
hi(0, "SignColumn", { fg = "#9587b5" })
hi(0, "Special", { fg = "#73b6d1" })
hi(0, "SpecialKey", { fg = "#9587b5" })
hi(0, "SpellBad", { sp = "#e82424", undercurl = true })
hi(0, "SpellCap", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellLocal", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellRare", { sp = "#ff9e3b", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#987bc4" })
hi(0, "StatusLine", { bg = "#16161d", fg = "#cbc086" })
hi(0, "StatusLineNC", { bg = "#16161d", fg = "#53517b" })
hi(0, "String", { fg = "#94bd5e" })
hi(0, "Substitute", { bg = "#c34043", fg = "#dfd7ac" })
hi(0, "TabLine", { bg = "#16161d", fg = "#9587b5" })
hi(0, "TabLineFill", { bg = "#1f1f28" })
hi(0, "TabLineSel", { bg = "#2a2a37", fg = "#cbc086" })
hi(0, "TelescopeBorder", { bg = "#1f1f28", fg = "#53517b" })
hi(0, "TelescopeMatching", { fg = "#73b6d1" })
hi(0, "TelescopeMultiIcon", { fg = "#ebc275" })
hi(0, "TelescopeMultiSelection", { fg = "#70ab9f" })
hi(0, "TelescopeNormal", {})
hi(0, "TelescopePreviewBlock", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewBorder", { bg = "#1f1f28", fg = "#53517b" })
hi(0, "TelescopePreviewCharDev", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewDate", { fg = "#789be2" })
hi(0, "TelescopePreviewDirectory", { fg = "#789be2" })
hi(0, "TelescopePreviewExecute", { fg = "#94bd5e" })
hi(0, "TelescopePreviewGroup", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewHyphen", { fg = "#53517b" })
hi(0, "TelescopePreviewLine", { bg = "#223249" })
hi(0, "TelescopePreviewLink", { fg = "#73b6d1" })
hi(0, "TelescopePreviewMatch", { bg = "#2d4f67", fg = "#dfd7ac" })
hi(0, "TelescopePreviewMessage", {})
hi(0, "TelescopePreviewMessageFillchar", {})
hi(0, "TelescopePreviewNormal", {})
hi(0, "TelescopePreviewPipe", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewRead", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewSize", { fg = "#94bd5e" })
hi(0, "TelescopePreviewSocket", { bold = true, fg = "#987bc4" })
hi(0, "TelescopePreviewSticky", { fg = "#987bc4", italic = true })
hi(0, "TelescopePreviewTitle", { fg = "#9587b5" })
hi(0, "TelescopePreviewUser", { fg = "#ff9e5f" })
hi(0, "TelescopePreviewWrite", { bold = true, fg = "#987bc4" })
hi(0, "TelescopePromptBorder", { bg = "#1f1f28", fg = "#53517b" })
hi(0, "TelescopePromptCounter", { fg = "#53517b" })
hi(0, "TelescopePromptNormal", {})
hi(0, "TelescopePromptPrefix", { fg = "#ebc275" })
hi(0, "TelescopePromptTitle", { fg = "#9587b5" })
hi(0, "TelescopeResultsBorder", { bg = "#1f1f28", fg = "#53517b" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsComment", { fg = "#737162", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#ff9e5f" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#2b3328" })
hi(0, "TelescopeResultsDiffChange", { bg = "#252535" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#43242b", fg = "#cc323b" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#53517b" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsFunction", { fg = "#789be2" })
hi(0, "TelescopeResultsIdentifier", { fg = "#ebc275" })
hi(0, "TelescopeResultsLineNr", { fg = "#53517b" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsNormal", {})
hi(0, "TelescopeResultsNumber", { fg = "#dc7699" })
hi(0, "TelescopeResultsOperator", { fg = "#c5a261" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#73b6d1" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsTitle", { fg = "#9587b5" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { fg = "#9587b5" })
hi(0, "Title", { bold = true, fg = "#789be2" })
hi(0, "Todo", { bg = "#658594", bold = true, fg = "#1e324f" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextLineNumber", { fg = "#9587b5" })
hi(0, "Type", { fg = "#70ab9f" })
hi(0, "Underlined", { fg = "#73b6d1", underline = true })
hi(0, "VertSplit", { link = "WinSeparator" })
hi(0, "Visual", { bg = "#223249" })
hi(0, "VisualNOS", { link = "Visual" })
hi(0, "WarningMsg", { fg = "#ff9e38" })
hi(0, "Whitespace", { fg = "#53517b" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#cbc086" })
hi(0, "WinBarNC", { fg = "#cbc086" })
hi(0, "WinSeparator", { fg = "#161522" })
hi(0, "debugBreakpoint", { fg = "#73b6d1" })
hi(0, "debugPC", { bg = "#43242b" })
hi(0, "diffAdded", { fg = "#709760" })
hi(0, "diffChanged", { fg = "#e2a351" })
hi(0, "diffDeleted", { fg = "#cc323b" })
hi(0, "diffNewFile", { fg = "#709760" })
hi(0, "diffOldFile", { fg = "#cc323b" })
hi(0, "diffRemoved", { fg = "#cc323b" })
hi(0, "healthError", { fg = "#ef0015" })
hi(0, "healthSuccess", { fg = "#94bd5e" })
hi(0, "healthWarning", { fg = "#ff9e38" })
hi(0, "illuminatedWord", { link = "LspReferenceText" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "lualine_a_command", { bg = "#c0a36e", fg = "#1e1e2e" })
hi(0, "lualine_a_inactive", { bg = "#16161d", fg = "#cbc086" })
hi(0, "lualine_a_insert", { bg = "#98bb6c", fg = "#1e1e2e" })
hi(0, "lualine_a_normal", { bg = "#7e9cd8", fg = "#161522" })
hi(0, "lualine_a_replace", { bg = "#ffa066", fg = "#1e1e2e" })
hi(0, "lualine_a_visual", { bg = "#957fb8", fg = "#1e1e2e" })
hi(0, "lualine_b_command", { bg = "#1f1f28", fg = "#c5a261" })
hi(0, "lualine_b_inactive", { bg = "#16161d", bold = true, fg = "#cbc086" })
hi(0, "lualine_b_insert", { bg = "#1f1f28", fg = "#94bd5e" })
hi(0, "lualine_b_normal", { bg = "#252535", fg = "#789be2" })
hi(0, "lualine_b_replace", { bg = "#1f1f28", fg = "#ff9e5f" })
hi(0, "lualine_b_visual", { bg = "#1f1f28", fg = "#987bc4" })
hi(0, "lualine_c_inactive", { bg = "#16161d", fg = "#cbc086" })
hi(0, "lualine_c_normal", { bg = "#2a2a37", fg = "#dfd7ac" })
hi(0, "lualine_x_filetype_DevIconTxt_command", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_inactive", { bg = "#16161d", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_insert", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_normal", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_replace", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_terminal", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "lualine_x_filetype_DevIconTxt_visual", { bg = "#2a2a37", fg = "#80e336" })
hi(0, "markdownCode", { fg = "#94bd5e" })
hi(0, "markdownCodeBlock", { fg = "#94bd5e" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#16161d"
g.terminal_color_1 = "#c34043"
g.terminal_color_2 = "#76946a"
g.terminal_color_3 = "#c0a36e"
g.terminal_color_4 = "#7e9cd8"
g.terminal_color_5 = "#957fb8"
g.terminal_color_6 = "#6a9589"
g.terminal_color_7 = "#c8c093"
g.terminal_color_8 = "#727169"
g.terminal_color_9 = "#e82424"
g.terminal_color_10 = "#98bb6c"
g.terminal_color_11 = "#e6c384"
g.terminal_color_12 = "#7fb4ca"
g.terminal_color_13 = "#938aa9"
g.terminal_color_14 = "#7aa89f"
g.terminal_color_15 = "#dcd7ba"
