-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "rose-pine"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "@character" })
hi(0, "@class", { fg = "#89d3e0" })
hi(0, "@constant.builtin", { fg = "#f96090" })
hi(0, "@constant.macro", { link = "@constant" })
hi(0, "@constructor", { fg = "#89d3e0" })
hi(0, "@field", { fg = "#89d3e0" })
hi(0, "@function.builtin", { fg = "#f96090" })
hi(0, "@function.macro", { link = "@function" })
hi(0, "@interface", { fg = "#89d3e0" })
hi(0, "@keyword.operator", { fg = "#9088bc" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method", { fg = "#f5b7b5" })
hi(0, "@namespace", { link = "@include" })
hi(0, "@parameter", { fg = "#c8a3f3" })
hi(0, "@property", { fg = "#89d3e0" })
hi(0, "@punctuation", { fg = "#6f659c" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "@punctuation" })
hi(0, "@regexp", { link = "String" })
hi(0, "@string.escape", { fg = "#1a7596" })
hi(0, "@string.special", { link = "@string" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { fg = "#c8a3f3" })
hi(0, "@tag.delimiter", { fg = "#9088bc" })
hi(0, "@text", { fg = "#e0ddf9" })
hi(0, "@text.danger", { fg = "#f96090" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#c8a3f3" })
hi(0, "@text.warning", { fg = "#febe62" })
hi(0, "@todo", { link = "Todo" })
hi(0, "@variable", { fg = "#e0ddf9" })
hi(0, "@variable.builtin", { fg = "#f96090" })
hi(0, "AlphaButtons", { fg = "#89d3e0" })
hi(0, "AlphaFooter", { fg = "#febe62" })
hi(0, "AlphaHeader", { fg = "#1a7596" })
hi(0, "AlphaShortcut", { fg = "#f5b7b5" })
hi(0, "Boolean", { fg = "#f5b7b5" })
hi(0, "BufferAlternate", {})
hi(0, "BufferAlternateADDED", {})
hi(0, "BufferAlternateCHANGED", {})
hi(0, "BufferAlternateDELETED", {})
hi(0, "BufferAlternateERROR", {})
hi(0, "BufferAlternateHINT", {})
hi(0, "BufferAlternateINFO", {})
hi(0, "BufferAlternateIcon", {})
hi(0, "BufferAlternateIndex", {})
hi(0, "BufferAlternateMod", {})
hi(0, "BufferAlternateNumber", {})
hi(0, "BufferAlternateSign", {})
hi(0, "BufferAlternateSignRight", {})
hi(0, "BufferAlternateTarget", {})
hi(0, "BufferAlternateWARN", {})
hi(0, "BufferCurrent", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferCurrentADDED", { bg = "#26233a", ctermfg = 82, fg = "#89d3e0" })
hi(0, "BufferCurrentCHANGED", { bg = "#26233a", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferCurrentDELETED", { bg = "#26233a", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferCurrentERROR", { bg = "#26233a", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferCurrentHINT", { bg = "#26233a", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferCurrentINFO", { bg = "#26233a", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferCurrentIcon", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferCurrentIndex", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferCurrentMod", { bg = "#26233a", fg = "#89d3e0" })
hi(0, "BufferCurrentNumber", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferCurrentSign", { bg = "#26233a", fg = "#9088bc" })
hi(0, "BufferCurrentSignRight", { bg = "#26233a", fg = "#9088bc" })
hi(0, "BufferCurrentTarget", { bg = "#26233a", fg = "#febe62" })
hi(0, "BufferCurrentWARN", { bg = "#26233a", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultAlternateIcon", {})
hi(0, "BufferDefaultAlternateNumber", {})
hi(0, "BufferDefaultAlternateSignRight", {})
hi(0, "BufferDefaultCurrent", { bg = "#26233a", ctermfg = 255, fg = "#e0ddf9" })
hi(0, "BufferDefaultCurrentADDED", { bg = "#26233a", ctermfg = 82, fg = "#89d3e0" })
hi(0, "BufferDefaultCurrentCHANGED", { bg = "#26233a", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferDefaultCurrentDELETED", { bg = "#26233a", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferDefaultCurrentERROR", { bg = "#26233a", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferDefaultCurrentHINT", { bg = "#26233a", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferDefaultCurrentINFO", { bg = "#26233a", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferDefaultCurrentIcon", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferDefaultCurrentIndex", { bg = "#26233a", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferDefaultCurrentMod", { bg = "#26233a", ctermfg = 178, fg = "#febe62" })
hi(0, "BufferDefaultCurrentNumber", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "BufferDefaultCurrentSign", { bg = "#26233a", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferDefaultCurrentSignRight", { bg = "#26233a", fg = "#9088bc" })
hi(0, "BufferDefaultCurrentTarget", { bg = "#26233a", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultCurrentWARN", { bg = "#26233a", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultInactive", { bg = "#1f1d2e", ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferDefaultInactiveADDED", { bg = "#1f1d2e", ctermfg = 82, fg = "#89d3e0" })
hi(0, "BufferDefaultInactiveCHANGED", { bg = "#1f1d2e", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferDefaultInactiveDELETED", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferDefaultInactiveERROR", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferDefaultInactiveHINT", { bg = "#1f1d2e", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferDefaultInactiveINFO", { bg = "#1f1d2e", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferDefaultInactiveIcon", { fg = "#9088bc" })
hi(0, "BufferDefaultInactiveIndex", { bg = "#1f1d2e", ctermfg = 240, fg = "#6f659c" })
hi(0, "BufferDefaultInactiveMod", { bg = "#1f1d2e", ctermfg = 178, fg = "#febe62" })
hi(0, "BufferDefaultInactiveNumber", { fg = "#9088bc" })
hi(0, "BufferDefaultInactiveSign", { bg = "#1f1d2e", ctermfg = 240, fg = "#6f659c" })
hi(0, "BufferDefaultInactiveSignRight", { fg = "#6f659c" })
hi(0, "BufferDefaultInactiveTarget", { bg = "#1f1d2e", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultInactiveWARN", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultOffset", { bg = "#191724", fg = "#19152b" })
hi(0, "BufferDefaultTabpageFill", { bg = "#1f1d2e", ctermfg = 102, fg = "#9088bc" })
hi(0, "BufferDefaultTabpages", { bg = "#1f1d2e", bold = true, ctermfg = 75, fg = "#febe62" })
hi(0, "BufferDefaultTabpagesSep", { bg = "#1f1d2e", bold = true, ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferDefaultVisible", { bg = "#1f1d2e", ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferDefaultVisibleADDED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultVisibleCHANGED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultVisibleDELETED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferDefaultVisibleERROR", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferDefaultVisibleHINT", { bg = "#1f1d2e", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferDefaultVisibleINFO", { bg = "#1f1d2e", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferDefaultVisibleIcon", { fg = "#9088bc" })
hi(0, "BufferDefaultVisibleIndex", { bg = "#1f1d2e", ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferDefaultVisibleMod", { bg = "#1f1d2e", ctermfg = 178, fg = "#febe62" })
hi(0, "BufferDefaultVisibleNumber", { fg = "#9088bc" })
hi(0, "BufferDefaultVisibleSign", { bg = "#1f1d2e", ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferDefaultVisibleSignRight", { fg = "#6f659c" })
hi(0, "BufferDefaultVisibleTarget", { bg = "#1f1d2e", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultVisibleWARN", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferInactive", { fg = "#9088bc" })
hi(0, "BufferInactiveADDED", { bg = "#1f1d2e", ctermfg = 82, fg = "#89d3e0" })
hi(0, "BufferInactiveCHANGED", { bg = "#1f1d2e", ctermfg = 75, fg = "#f5b7b5" })
hi(0, "BufferInactiveDELETED", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferInactiveERROR", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferInactiveHINT", { bg = "#1f1d2e", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferInactiveINFO", { bg = "#1f1d2e", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferInactiveIcon", { fg = "#9088bc" })
hi(0, "BufferInactiveIndex", { fg = "#9088bc" })
hi(0, "BufferInactiveMod", { fg = "#89d3e0" })
hi(0, "BufferInactiveNumber", { fg = "#9088bc" })
hi(0, "BufferInactiveSign", { fg = "#6f659c" })
hi(0, "BufferInactiveSignRight", { fg = "#6f659c" })
hi(0, "BufferInactiveTarget", { fg = "#febe62" })
hi(0, "BufferInactiveWARN", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferOffset", { bg = "#191724", fg = "#19152b" })
hi(0, "BufferScrollArrow", { bg = "#1f1d2e", bold = true, ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferTabpageFill", { bg = "#191724", fg = "#19152b" })
hi(0, "BufferTabpages", { bg = "#1f1d2e", bold = true, ctermfg = 75, fg = "#febe62" })
hi(0, "BufferTabpagesSep", { bg = "#1f1d2e", bold = true, ctermfg = 255, fg = "#9088bc" })
hi(0, "BufferVisible", { fg = "#9088bc" })
hi(0, "BufferVisibleADDED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferVisibleCHANGED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferVisibleDELETED", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "BufferVisibleERROR", { bg = "#1f1d2e", ctermfg = 124, fg = "#f96090" })
hi(0, "BufferVisibleHINT", { bg = "#1f1d2e", ctermfg = 168, fg = "#c8a3f3" })
hi(0, "BufferVisibleINFO", { bg = "#1f1d2e", ctermfg = 217, fg = "#89d3e0" })
hi(0, "BufferVisibleIcon", { fg = "#9088bc" })
hi(0, "BufferVisibleIndex", { fg = "#9088bc" })
hi(0, "BufferVisibleMod", { fg = "#89d3e0" })
hi(0, "BufferVisibleNumber", { fg = "#9088bc" })
hi(0, "BufferVisibleSign", { fg = "#6f659c" })
hi(0, "BufferVisibleSignRight", { fg = "#6f659c" })
hi(0, "BufferVisibleTarget", { fg = "#febe62" })
hi(0, "BufferVisibleWARN", { bg = "#1f1d2e", ctermfg = 208, fg = "#febe62" })
hi(0, "Character", { fg = "#febe62" })
hi(0, "CmpItemAbbr", { fg = "#9088bc" })
hi(0, "CmpItemAbbrDefault", { fg = "#9088bc" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#9088bc", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6f659c" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e0ddf9" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#9088bc" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e0ddf9" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9088bc" })
hi(0, "CmpItemKind", { fg = "#9088bc" })
hi(0, "CmpItemKindClass", { fg = "#1a7596" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#9088bc" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#9088bc" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#9088bc" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { ctermfg = 6, fg = "#01ff01" })
hi(0, "CmpItemKindDefault", { fg = "#f5b7b5" })
hi(0, "CmpItemKindEnum", { fg = "#9088bc" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#9088bc" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#9088bc" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#9088bc" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#9088bc" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#9088bc" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#f5b7b5" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#89d3e0" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#9088bc" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#c8a3f3" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#9088bc" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#9088bc" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#9088bc" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#9088bc" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#febe62" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#9088bc" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#9088bc" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#9088bc" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#9088bc" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#9088bc" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#e0ddf9" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#9088bc" })
hi(0, "CmpItemMenuDefault", { fg = "#9088bc" })
hi(0, "ColorColumn", { bg = "#26233a" })
hi(0, "Comment", { fg = "#6f659c" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#1a7596" })
hi(0, "Constant", { fg = "#febe62" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#524f67", fg = "#e0ddf9" })
hi(0, "CursorColumn", { bg = "#21202e" })
hi(0, "CursorLine", { bg = "#21202e" })
hi(0, "CursorLineNr", { fg = "#e0ddf9" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#febe62" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#6f659c" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#89d3e0" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { link = "DapUIBreakpointsPath" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#89d3e0" })
hi(0, "DapUINormalNC", {})
hi(0, "DapUIPlayPause", { fg = "#a5ff5e" })
hi(0, "DapUIPlayPauseNC", { fg = "#a5ff5e" })
hi(0, "DapUIRestart", { fg = "#a5ff5e" })
hi(0, "DapUIRestartNC", { fg = "#a5ff5e" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#c8a3f3" })
hi(0, "DapUIStepBack", { fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { fg = "#00f1f5" })
hi(0, "DapUIStepInto", { fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOut", { fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOver", { fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { fg = "#00f1f5" })
hi(0, "DapUIStop", { fg = "#f70067" })
hi(0, "DapUIStopNC", { fg = "#f70067" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#febe62" })
hi(0, "DapUIType", { fg = "#d680ff" })
hi(0, "DapUIUnavailable", { fg = "#424242" })
hi(0, "DapUIUnavailableNC", { fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { fg = "#f96090" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#febe62" })
hi(0, "DashboardFooter", { fg = "#c8a3f3" })
hi(0, "DashboardHeader", { fg = "#1a7596" })
hi(0, "DashboardShortcut", { fg = "#f96090" })
hi(0, "Debug", { fg = "#f5b7b5" })
hi(0, "Define", { fg = "#c8a3f3" })
hi(0, "DefinitionCount", { fg = "#f5b7b5" })
hi(0, "DefinitionIcon", { fg = "#f5b7b5" })
hi(0, "DefintionPreviewTitle", { bold = true, fg = "#f5b7b5" })
hi(0, "Delimiter", { fg = "#9088bc" })
hi(0, "DiagnosticDefaultError", { fg = "#f96090" })
hi(0, "DiagnosticDefaultHint", { fg = "#c8a3f3" })
hi(0, "DiagnosticDefaultInfo", { fg = "#89d3e0" })
hi(0, "DiagnosticDefaultWarn", { fg = "#febe62" })
hi(0, "DiagnosticError", { fg = "#f96090" })
hi(0, "DiagnosticFloatingError", { fg = "#f96090" })
hi(0, "DiagnosticFloatingHint", { fg = "#c8a3f3" })
hi(0, "DiagnosticFloatingInfo", { fg = "#89d3e0" })
hi(0, "DiagnosticFloatingWarn", { fg = "#febe62" })
hi(0, "DiagnosticHint", { fg = "#c8a3f3" })
hi(0, "DiagnosticInfo", { fg = "#89d3e0" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#76f47a" })
hi(0, "DiagnosticSignError", { fg = "#f96090" })
hi(0, "DiagnosticSignHint", { fg = "#c8a3f3" })
hi(0, "DiagnosticSignInfo", { fg = "#89d3e0" })
hi(0, "DiagnosticSignWarn", { fg = "#febe62" })
hi(0, "DiagnosticStatusLineError", { bg = "#1f1d2e", fg = "#f96090" })
hi(0, "DiagnosticStatusLineHint", { bg = "#1f1d2e", fg = "#c8a3f3" })
hi(0, "DiagnosticStatusLineInfo", { bg = "#1f1d2e", fg = "#89d3e0" })
hi(0, "DiagnosticStatusLineWarn", { bg = "#1f1d2e", fg = "#febe62" })
hi(0, "DiagnosticUnderlineError", { sp = "#eb6f92", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c4a7e7", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#9ccfd8", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f6c177", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#f96090" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#c8a3f3" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#89d3e0" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#febe62" })
hi(0, "DiagnosticWarn", { fg = "#febe62" })
hi(0, "DiffAdd", { bg = "#333c48", blend = 20 })
hi(0, "DiffChange", { bg = "#26233a" })
hi(0, "DiffDelete", { bg = "#43293a", blend = 20 })
hi(0, "DiffText", { bg = "#433842", blend = 20 })
hi(0, "Directory", { fg = "#89d3e0" })
hi(0, "Error", { fg = "#f96090" })
hi(0, "ErrorMsg", { bold = true, fg = "#f96090" })
hi(0, "Exception", { fg = "#1a7596" })
hi(0, "Float", { fg = "#febe62" })
hi(0, "FloatBorder", { fg = "#403961" })
hi(0, "FloatTitle", { fg = "#6f659c" })
hi(0, "FlutterToolsOutlineIndentGuides", { fg = "#6f659c" })
hi(0, "FoldColumn", { fg = "#6f659c" })
hi(0, "Folded", { fg = "#e0ddf9" })
hi(0, "Function", { fg = "#f5b7b5" })
hi(0, "GitSignsAdd", { bg = "#191724", fg = "#89d3e0" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#333c48", blend = 20 })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { bg = "#191724", fg = "#89d3e0" })
hi(0, "GitSignsAddPreview", { bg = "#333c48", blend = 20 })
hi(0, "GitSignsChange", { bg = "#191724", fg = "#f5b7b5" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#26233a" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { bg = "#191724", fg = "#f5b7b5" })
hi(0, "GitSignsChangedelete", { bg = "#191724", fg = "#f5b7b5" })
hi(0, "GitSignsChangedeleteLn", { bg = "#26233a" })
hi(0, "GitSignsChangedeleteNr", { bg = "#191724", fg = "#f5b7b5" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#6f659c" })
hi(0, "GitSignsDelete", { bg = "#191724", fg = "#f96090" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { bg = "#191724", fg = "#f96090" })
hi(0, "GitSignsDeletePreview", { bg = "#43293a", blend = 20 })
hi(0, "GitSignsDeleteVirtLn", { bg = "#43293a", blend = 20 })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { bg = "#191724", fg = "#446970" })
hi(0, "GitSignsStagedAddLn", { bg = "#333c48" })
hi(0, "GitSignsStagedAddNr", { bg = "#191724", fg = "#446970" })
hi(0, "GitSignsStagedChange", { bg = "#191724", fg = "#845755" })
hi(0, "GitSignsStagedChangeLn", { bg = "#26233a" })
hi(0, "GitSignsStagedChangeNr", { bg = "#191724", fg = "#845755" })
hi(0, "GitSignsStagedChangedelete", { bg = "#191724", fg = "#845755" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#26233a" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#191724", fg = "#845755" })
hi(0, "GitSignsStagedDelete", { bg = "#191724", fg = "#7e2d48" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#191724", fg = "#7e2d48" })
hi(0, "GitSignsStagedTopdelete", { bg = "#191724", fg = "#7e2d48" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#191724", fg = "#7e2d48" })
hi(0, "GitSignsTopdelete", { bg = "#191724", fg = "#f96090" })
hi(0, "GitSignsTopdeleteNr", { bg = "#191724", fg = "#f96090" })
hi(0, "GitSignsUntracked", { bg = "#191724", fg = "#89d3e0" })
hi(0, "GitSignsUntrackedLn", { bg = "#333c48", blend = 20 })
hi(0, "GitSignsUntrackedNr", { bg = "#191724", fg = "#89d3e0" })
hi(0, "GitSignsVirtLnum", { bg = "#43293a", blend = 20 })
hi(0, "HopNextKey", { fg = "#f96090" })
hi(0, "HopNextKey1", { fg = "#89d3e0" })
hi(0, "HopNextKey2", { fg = "#1a7596" })
hi(0, "HopUnmatched", { fg = "#524b7a" })
hi(0, "Identifier", { fg = "#f5b7b5" })
hi(0, "IncSearch", { bg = "#ebbcba", fg = "#19152b" })
hi(0, "Include", { fg = "#1a7596" })
hi(0, "IndentBlanklineChar", { fg = "#6f659c", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#6f659c", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#6f659c", nocombine = true })
hi(0, "Keyword", { fg = "#1a7596" })
hi(0, "Label", { fg = "#89d3e0" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { bg = "#31748f", fg = "#19152b" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#6f659c" })
hi(0, "LspCodeLens", { fg = "#9088bc" })
hi(0, "LspCodeLensSeparator", { fg = "#524b7a" })
hi(0, "LspFloatWinBorder", { fg = "#403961" })
hi(0, "LspInfoBorder", { fg = "#89d3e0" })
hi(0, "LspInfoFiletype", { fg = "#89d3e0" })
hi(0, "LspInfoList", { fg = "#f5b7b5" })
hi(0, "LspInfoTip", { fg = "#6f659c" })
hi(0, "LspInfoTitle", { fg = "#e0ddf9" })
hi(0, "LspReferenceRead", { bg = "#403d52" })
hi(0, "LspReferenceText", { bg = "#403d52" })
hi(0, "LspReferenceWrite", { bg = "#403d52" })
hi(0, "LspSagaAutoPreview", { fg = "#9088bc" })
hi(0, "LspSagaCodeActionBorder", { fg = "#403961" })
hi(0, "LspSagaCodeActionContent", { fg = "#89d3e0" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#febe62" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#403961" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#403961" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#febe62" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#febe62" })
hi(0, "LspSagaHoverBorder", { fg = "#403961" })
hi(0, "LspSagaLspFinderBorder", { fg = "#403961" })
hi(0, "LspSagaRenameBorder", { fg = "#1a7596" })
hi(0, "LspSagaRenamePromptPrefix", { fg = "#f96090" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#1a7596" })
hi(0, "LspSignatureActiveParameter", { bg = "#26233a" })
hi(0, "Macro", { fg = "#c8a3f3" })
hi(0, "MatchParen", { bg = "#403d52", fg = "#e0ddf9" })
hi(0, "MiniIndentscopeSymbol", { fg = "#403961" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#403961" })
hi(0, "ModeMsg", { fg = "#9088bc" })
hi(0, "ModesCopy", { bg = "#f6c177" })
hi(0, "ModesDelete", { bg = "#eb6f92" })
hi(0, "ModesInsert", { bg = "#9ccfd8" })
hi(0, "ModesVisual", { bg = "#c4a7e7" })
hi(0, "MoreMsg", { fg = "#c8a3f3" })
hi(0, "MyCopilotIcon", { fg = "#ffa509" })
hi(0, "NavicIconsArray", { fg = "#febe62" })
hi(0, "NavicIconsBoolean", { fg = "#f5b7b5" })
hi(0, "NavicIconsClass", { fg = "#89d3e0" })
hi(0, "NavicIconsConstant", { fg = "#febe62" })
hi(0, "NavicIconsConstructor", { fg = "#febe62" })
hi(0, "NavicIconsEnum", { fg = "#febe62" })
hi(0, "NavicIconsEnumMember", { fg = "#89d3e0" })
hi(0, "NavicIconsEvent", { fg = "#febe62" })
hi(0, "NavicIconsField", { fg = "#89d3e0" })
hi(0, "NavicIconsFile", { fg = "#19152b" })
hi(0, "NavicIconsFunction", { fg = "#1a7596" })
hi(0, "NavicIconsInterface", { fg = "#89d3e0" })
hi(0, "NavicIconsKey", { fg = "#c8a3f3" })
hi(0, "NavicIconsKeyword", { fg = "#1a7596" })
hi(0, "NavicIconsMethod", { fg = "#c8a3f3" })
hi(0, "NavicIconsModule", { fg = "#f5b7b5" })
hi(0, "NavicIconsNamespace", { fg = "#19152b" })
hi(0, "NavicIconsNull", { fg = "#f96090" })
hi(0, "NavicIconsNumber", { fg = "#febe62" })
hi(0, "NavicIconsObject", { fg = "#febe62" })
hi(0, "NavicIconsOperator", { fg = "#9088bc" })
hi(0, "NavicIconsPackage", { fg = "#19152b" })
hi(0, "NavicIconsProperty", { fg = "#89d3e0" })
hi(0, "NavicIconsString", { fg = "#febe62" })
hi(0, "NavicIconsStruct", { fg = "#89d3e0" })
hi(0, "NavicIconsTypeParameter", { fg = "#89d3e0" })
hi(0, "NavicIconsVariable", { fg = "#e0ddf9" })
hi(0, "NavicSeparator", { fg = "#9088bc" })
hi(0, "NavicText", { fg = "#9088bc" })
hi(0, "NeoTreeGitAdded", { fg = "#89d3e0" })
hi(0, "NeoTreeGitConflict", { fg = "#c8a3f3" })
hi(0, "NeoTreeGitDeleted", { fg = "#f96090" })
hi(0, "NeoTreeGitIgnored", { fg = "#6f659c" })
hi(0, "NeoTreeGitModified", { fg = "#f5b7b5" })
hi(0, "NeoTreeGitRenamed", { fg = "#1a7596" })
hi(0, "NeoTreeGitUntracked", { fg = "#febe62" })
hi(0, "NeoTreeTitleBar", { bg = "#31748f", fg = "#1f1b37" })
hi(0, "NeogitDiffAddHighlight", { bg = "#403d52", fg = "#89d3e0" })
hi(0, "NeogitDiffContextHighlight", { bg = "#21202e" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#403d52", fg = "#f96090" })
hi(0, "NeogitHunkHeader", { bg = "#21202e" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#21202e" })
hi(0, "NeorgHeading1Prefix", { bold = true, fg = "#c8a3f3" })
hi(0, "NeorgHeading1Title", { link = "NeorgHeading1Prefix" })
hi(0, "NeorgHeading2Prefix", { bold = true, fg = "#89d3e0" })
hi(0, "NeorgHeading2Title", { link = "NeorgHeading2Prefix" })
hi(0, "NeorgHeading3Prefix", { bold = true, fg = "#f5b7b5" })
hi(0, "NeorgHeading3Title", { link = "NeorgHeading3Prefix" })
hi(0, "NeorgHeading4Prefix", { bold = true, fg = "#febe62" })
hi(0, "NeorgHeading4Title", { link = "NeorgHeading4Prefix" })
hi(0, "NeorgHeading5Prefix", { bold = true, fg = "#1a7596" })
hi(0, "NeorgHeading5Title", { link = "NeorgHeading5Prefix" })
hi(0, "NeorgHeading6Prefix", { bold = true, fg = "#89d3e0" })
hi(0, "NeorgHeading6Title", { link = "NeorgHeading6Prefix" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#e0ddf9" })
hi(0, "NoiceCursor", { bg = "#e0def4", fg = "#524b7a" })
hi(0, "NonText", { fg = "#6f659c" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#e0ddf9" })
hi(0, "NotifyDEBUGBorder", { fg = "#6f659c" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#f96090" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#89d3e0" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#c8a3f3" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#febe62" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NullLsInfoBorder", {})
hi(0, "NullLsInfoHeader", { fg = "#89d3e0" })
hi(0, "NullLsInfoSources", { fg = "#e0ddf9" })
hi(0, "NullLsInfoTitle", { fg = "#89d3e0" })
hi(0, "Number", { fg = "#febe62" })
hi(0, "NvimInternalError", { bg = "#eb6f92", fg = "#ffffff" })
hi(0, "NvimTreeBookmark", { fg = "#1a7596" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#6f659c" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#1a7596" })
hi(0, "NvimTreeFileDeleted", { fg = "#f96090" })
hi(0, "NvimTreeFileDirty", { fg = "#f5b7b5" })
hi(0, "NvimTreeFileMerge", { fg = "#c8a3f3" })
hi(0, "NvimTreeFileNew", { fg = "#89d3e0" })
hi(0, "NvimTreeFileRenamed", { fg = "#1a7596" })
hi(0, "NvimTreeFileStaged", { fg = "#c8a3f3" })
hi(0, "NvimTreeFolderIcon", { fg = "#9088bc" })
hi(0, "NvimTreeFolderName", { fg = "#89d3e0" })
hi(0, "NvimTreeGitDeleted", { fg = "#f96090" })
hi(0, "NvimTreeGitDirty", { fg = "#f5b7b5" })
hi(0, "NvimTreeGitIgnored", { fg = "#6f659c" })
hi(0, "NvimTreeGitMerge", { fg = "#c8a3f3" })
hi(0, "NvimTreeGitNew", { fg = "#89d3e0" })
hi(0, "NvimTreeGitRenamed", { fg = "#1a7596" })
hi(0, "NvimTreeGitStaged", { fg = "#c8a3f3" })
hi(0, "NvimTreeImageFile", { fg = "#e0ddf9" })
hi(0, "NvimTreeIndentMarker", { fg = "#7694c5" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#c8a3f3" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeNormal", { fg = "#e0ddf9" })
hi(0, "NvimTreeOpenedFile", { bg = "#403d52", fg = "#e0ddf9" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { fg = "#c8a3f3" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#f5b7b5" })
hi(0, "NvimTreeWindowPicker", { bg = "#2e202f", blend = 10, fg = "#f96090" })
hi(0, "Operator", { fg = "#9088bc" })
hi(0, "Pmenu", { fg = "#9088bc" })
hi(0, "PmenuSbar", { bg = "#21202e" })
hi(0, "PmenuSel", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "PmenuThumb", { bg = "#403d52" })
hi(0, "PounceAccept", { bg = "#524f67", fg = "#f96090" })
hi(0, "PounceAcceptBest", { bg = "#f6c177", fg = "#19152b" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#c8a3f3" })
hi(0, "PreProc", { fg = "#c8a3f3" })
hi(0, "Question", { fg = "#febe62" })
hi(0, "RedrawDebugClear", { bg = "#f6c177", fg = "#ffffff" })
hi(0, "RedrawDebugComposed", { bg = "#31748f", fg = "#ffffff" })
hi(0, "RedrawDebugRecompose", { bg = "#eb6f92", fg = "#ffffff" })
hi(0, "ReferencesCount", { fg = "#f5b7b5" })
hi(0, "ReferencesIcon", { fg = "#f5b7b5" })
hi(0, "Repeat", { fg = "#1a7596" })
hi(0, "SagaShadow", { bg = "#26233a" })
hi(0, "Search", { bg = "#403d52" })
hi(0, "SignAdd", { link = "GitSignsAdd" })
hi(0, "SignChange", { link = "GitSignsChange" })
hi(0, "SignColumn", { fg = "#e0ddf9" })
hi(0, "SignDelete", { link = "GitSignsDelete" })
hi(0, "Special", { fg = "#f5b7b5" })
hi(0, "SpecialChar", { fg = "#f5b7b5" })
hi(0, "SpecialComment", { fg = "#c8a3f3" })
hi(0, "SpecialKey", { fg = "#89d3e0" })
hi(0, "SpellBad", { sp = "#908caa", undercurl = true })
hi(0, "SpellCap", { sp = "#908caa", undercurl = true })
hi(0, "SpellLocal", { sp = "#908caa", undercurl = true })
hi(0, "SpellRare", { sp = "#908caa", undercurl = true })
hi(0, "Statement", { fg = "#1a7596" })
hi(0, "StatusLine", { bg = "#1f1d2e", fg = "#9088bc" })
hi(0, "StatusLineNC", { bg = "#191724", fg = "#6f659c" })
hi(0, "StatusLineTerm", { link = "StatusLine" })
hi(0, "StatusLineTermNC", { link = "StatusLineNC" })
hi(0, "StorageClass", { fg = "#89d3e0" })
hi(0, "String", { fg = "#febe62" })
hi(0, "Structure", { fg = "#89d3e0" })
hi(0, "TabLine", { bg = "#1f1d2e", fg = "#9088bc" })
hi(0, "TabLineFill", { bg = "#1f1d2e" })
hi(0, "TabLineSel", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "Tag", { fg = "#89d3e0" })
hi(0, "TargetWord", { fg = "#c8a3f3" })
hi(0, "TelescopeBorder", { fg = "#403961" })
hi(0, "TelescopeMatching", { fg = "#f5b7b5" })
hi(0, "TelescopeMultiIcon", { fg = "#f5b7b5" })
hi(0, "TelescopeMultiSelection", { fg = "#89d3e0" })
hi(0, "TelescopeNormal", {})
hi(0, "TelescopePreviewBlock", { fg = "#febe62" })
hi(0, "TelescopePreviewBorder", { fg = "#403961" })
hi(0, "TelescopePreviewCharDev", { fg = "#febe62" })
hi(0, "TelescopePreviewDate", { fg = "#89d3e0" })
hi(0, "TelescopePreviewDirectory", { fg = "#89d3e0" })
hi(0, "TelescopePreviewExecute", { fg = "#febe62" })
hi(0, "TelescopePreviewGroup", { fg = "#febe62" })
hi(0, "TelescopePreviewHyphen", { fg = "#6f659c" })
hi(0, "TelescopePreviewLine", { bg = "#403d52" })
hi(0, "TelescopePreviewLink", { fg = "#f5b7b5" })
hi(0, "TelescopePreviewMatch", { bg = "#403d52" })
hi(0, "TelescopePreviewMessage", {})
hi(0, "TelescopePreviewMessageFillchar", {})
hi(0, "TelescopePreviewNormal", {})
hi(0, "TelescopePreviewPipe", { fg = "#febe62" })
hi(0, "TelescopePreviewRead", { fg = "#febe62" })
hi(0, "TelescopePreviewSize", { fg = "#febe62" })
hi(0, "TelescopePreviewSocket", { fg = "#1a7596" })
hi(0, "TelescopePreviewSticky", { fg = "#1a7596" })
hi(0, "TelescopePreviewTitle", { fg = "#9088bc" })
hi(0, "TelescopePreviewUser", { fg = "#febe62" })
hi(0, "TelescopePreviewWrite", { fg = "#1a7596" })
hi(0, "TelescopePromptBorder", { fg = "#403961" })
hi(0, "TelescopePromptCounter", { fg = "#6f659c" })
hi(0, "TelescopePromptNormal", { fg = "#e0ddf9" })
hi(0, "TelescopePromptPrefix", { fg = "#9088bc" })
hi(0, "TelescopePromptTitle", { fg = "#9088bc" })
hi(0, "TelescopeResultsBorder", { fg = "#403961" })
hi(0, "TelescopeResultsClass", { fg = "#f5b7b5" })
hi(0, "TelescopeResultsComment", { fg = "#6f659c" })
hi(0, "TelescopeResultsConstant", { fg = "#febe62" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#333c48", blend = 20 })
hi(0, "TelescopeResultsDiffChange", { bg = "#26233a" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#43293a", blend = 20 })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#6f659c" })
hi(0, "TelescopeResultsField", { fg = "#f5b7b5" })
hi(0, "TelescopeResultsFunction", { fg = "#f5b7b5" })
hi(0, "TelescopeResultsIdentifier", { fg = "#f5b7b5" })
hi(0, "TelescopeResultsLineNr", { fg = "#6f659c" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", {})
hi(0, "TelescopeResultsNumber", { fg = "#febe62" })
hi(0, "TelescopeResultsOperator", { fg = "#9088bc" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#c8a3f3" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#9088bc" })
hi(0, "TelescopeResultsVariable", { fg = "#f5b7b5" })
hi(0, "TelescopeSelection", { bg = "#26233a", fg = "#e0ddf9" })
hi(0, "TelescopeSelectionCaret", { bg = "#26233a", fg = "#f5b7b5" })
hi(0, "TelescopeTitle", { fg = "#9088bc" })
hi(0, "Title", { fg = "#e0ddf9" })
hi(0, "Todo", { fg = "#c8a3f3" })
hi(0, "Type", { fg = "#89d3e0" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#403961" })
hi(0, "VimwikiHR", { fg = "#9088bc" })
hi(0, "VimwikiHeader1", { bold = true, fg = "#c8a3f3" })
hi(0, "VimwikiHeader2", { bold = true, fg = "#89d3e0" })
hi(0, "VimwikiHeader3", { bold = true, fg = "#f5b7b5" })
hi(0, "VimwikiHeader4", { bold = true, fg = "#febe62" })
hi(0, "VimwikiHeader5", { bold = true, fg = "#1a7596" })
hi(0, "VimwikiHeader6", { bold = true, fg = "#89d3e0" })
hi(0, "VimwikiHeaderChar", { fg = "#1a7596" })
hi(0, "VimwikiLink", { fg = "#c8a3f3", underline = true })
hi(0, "VimwikiList", { fg = "#c8a3f3" })
hi(0, "VimwikiNoExistsLink", { fg = "#f96090" })
hi(0, "Visual", { bg = "#403d52" })
hi(0, "WarningMsg", { fg = "#febe62" })
hi(0, "WhichKey", { fg = "#c8a3f3" })
hi(0, "WhichKeyDesc", { fg = "#febe62" })
hi(0, "WhichKeyGroup", { fg = "#89d3e0" })
hi(0, "WhichKeySeparator", { fg = "#9088bc" })
hi(0, "WhichKeyValue", { fg = "#f5b7b5" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "healthError", { fg = "#f96090" })
hi(0, "healthSuccess", { fg = "#89d3e0" })
hi(0, "healthWarning", { fg = "#febe62" })
hi(0, "htmlArg", { fg = "#c8a3f3" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlEndTag", { fg = "#9088bc" })
hi(0, "htmlH1", { bold = true, fg = "#c8a3f3" })
hi(0, "htmlH2", { bold = true, fg = "#89d3e0" })
hi(0, "htmlH3", { bold = true, fg = "#f5b7b5" })
hi(0, "htmlH4", { bold = true, fg = "#febe62" })
hi(0, "htmlH5", { bold = true, fg = "#1a7596" })
hi(0, "htmlLink", { fg = "#c8a3f3" })
hi(0, "htmlTag", { fg = "#9088bc" })
hi(0, "htmlTagN", { fg = "#e0ddf9" })
hi(0, "htmlTagName", { fg = "#89d3e0" })
hi(0, "illuminatedWord", { link = "LspReferenceText" })
hi(0, "lualine_a_command", { bg = "#eb6f92", bold = true, fg = "#19152b" })
hi(0, "lualine_a_inactive", { bg = "#191724", bold = true, fg = "#6f659c" })
hi(0, "lualine_a_insert", { bg = "#9ccfd8", bold = true, fg = "#19152b" })
hi(0, "lualine_a_normal", { bg = "#ebbcba", bold = true, fg = "#19152b" })
hi(0, "lualine_a_replace", { bg = "#31748f", bold = true, fg = "#19152b" })
hi(0, "lualine_a_visual", { bg = "#c4a7e7", bold = true, fg = "#19152b" })
hi(0, "lualine_b_command", { bg = "#26233a", fg = "#f96090" })
hi(0, "lualine_b_inactive", { bg = "#191724", fg = "#6f659c" })
hi(0, "lualine_b_insert", { bg = "#26233a", fg = "#89d3e0" })
hi(0, "lualine_b_normal", { bg = "#26233a", fg = "#f5b7b5" })
hi(0, "lualine_b_replace", { bg = "#26233a", fg = "#1a7596" })
hi(0, "lualine_b_visual", { bg = "#26233a", fg = "#c8a3f3" })
hi(0, "lualine_c_command", { bg = "#191724", fg = "#e0ddf9" })
hi(0, "lualine_c_inactive", { bg = "#191724", fg = "#6f659c" })
hi(0, "lualine_c_insert", { bg = "#191724", fg = "#e0ddf9" })
hi(0, "lualine_c_normal", { bg = "#191724", fg = "#e0ddf9" })
hi(0, "lualine_c_replace", { bg = "#191724", fg = "#e0ddf9" })
hi(0, "lualine_c_visual", { bg = "#191724", fg = "#e0ddf9" })
hi(0, "lualine_x_filetype_DevIconDart_command", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_inactive", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_insert", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_normal", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_replace", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_terminal", { bg = "#191724", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_visual", { bg = "#191724", fg = "#01589d" })
hi(0, "markdownDelimiter", { fg = "#9088bc" })
hi(0, "markdownH1", { bold = true, fg = "#c8a3f3" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#89d3e0" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#f5b7b5" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#febe62" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#1a7596" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#89d3e0" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { fg = "#c8a3f3", sp = "#c4a7e7", underline = true })
hi(0, "markdownUrl", { link = "markdownLinkText" })
hi(0, "mkdCode", { fg = "#89d3e0" })
hi(0, "mkdCodeDelimiter", { fg = "#f5b7b5" })
hi(0, "mkdCodeEnd", { fg = "#89d3e0" })
hi(0, "mkdCodeStart", { fg = "#89d3e0" })
hi(0, "mkdFootnotes", { fg = "#89d3e0" })
hi(0, "mkdID", { fg = "#89d3e0", underline = true })
hi(0, "mkdInlineURL", { fg = "#c8a3f3", underline = true })
hi(0, "mkdLink", { link = "mkdInlineURL" })
hi(0, "mkdLinkDef", { link = "mkdInlineURL" })
hi(0, "mkdListItemLine", { fg = "#e0ddf9" })
hi(0, "mkdRule", { fg = "#9088bc" })
hi(0, "mkdURL", { link = "mkdInlineURL" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#26233a"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#31748f"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ebbcba"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#31748f"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ebbcba"
g.terminal_color_15 = "#e0def4"
