-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tokyonight"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#7acfff" })
hi(0, "@attribute", { fg = "#7acfff" })
hi(0, "@boolean", { fg = "#ff9c5d" })
hi(0, "@character", { fg = "#94d243" })
hi(0, "@character.special", { fg = "#00c4e1" })
hi(0, "@comment", { fg = "#4d59a8" })
hi(0, "@conditional", { fg = "#be94ff" })
hi(0, "@constant", { fg = "#ff9c5d" })
hi(0, "@constant.builtin", { fg = "#00c4e1" })
hi(0, "@constant.macro", { fg = "#7acfff" })
hi(0, "@constructor", { fg = "#be94ff" })
hi(0, "@constructor.tsx", { fg = "#00c4e1" })
hi(0, "@debug", { fg = "#ff9c5d" })
hi(0, "@define", { fg = "#7acfff" })
hi(0, "@exception", { fg = "#be94ff" })
hi(0, "@field", { fg = "#48e0cc" })
hi(0, "@float", { fg = "#ff9c5d" })
hi(0, "@function", { fg = "#70a0ff" })
hi(0, "@function.builtin", { fg = "#00c4e1" })
hi(0, "@function.call", { fg = "#70a0ff" })
hi(0, "@function.macro", { fg = "#7acfff" })
hi(0, "@include", { fg = "#7acfff" })
hi(0, "@keyword", { fg = "#a272ee" })
hi(0, "@keyword.coroutine", { fg = "#a272ee" })
hi(0, "@keyword.function", { fg = "#be94ff" })
hi(0, "@keyword.operator", { fg = "#86ddff" })
hi(0, "@keyword.return", { fg = "#a272ee" })
hi(0, "@label", { fg = "#70a0ff" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.interface", { fg = "#39d9f2" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string.rust", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#db4b4b", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#00a5c1" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method", { fg = "#70a0ff" })
hi(0, "@method.call", { fg = "#70a0ff" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number", { fg = "#ff9c5d" })
hi(0, "@operator", { fg = "#86ddff" })
hi(0, "@parameter", { fg = "#ecab44" })
hi(0, "@preproc", { fg = "#7acfff" })
hi(0, "@property", { fg = "#48e0cc" })
hi(0, "@punctuation.bracket", { fg = "#a4afe7" })
hi(0, "@punctuation.delimiter", { fg = "#86ddff" })
hi(0, "@punctuation.special", { fg = "#86ddff" })
hi(0, "@punctuation.special.markdown", { bold = true, fg = "#ff9c5d" })
hi(0, "@repeat", { fg = "#be94ff" })
hi(0, "@storageclass", { fg = "#00c4e1" })
hi(0, "@string", { fg = "#94d243" })
hi(0, "@string.documentation", { fg = "#ecab44" })
hi(0, "@string.escape", { fg = "#be94ff" })
hi(0, "@string.regex", { fg = "#a0fdfc" })
hi(0, "@string.special", { fg = "#00c4e1" })
hi(0, "@symbol", { fg = "#be94ff" })
hi(0, "@tag", { fg = "#be94ff" })
hi(0, "@tag.attribute", { fg = "#48e0cc" })
hi(0, "@tag.delimiter", { fg = "#00c4e1" })
hi(0, "@tag.delimiter.tsx", { fg = "#5279d9" })
hi(0, "@tag.tsx", { fg = "#ff6588" })
hi(0, "@text", {})
hi(0, "@text.danger", { bg = "#db4b4b", fg = "#1f254c" })
hi(0, "@text.diff.add", { link = "DiffAdd" })
hi(0, "@text.diff.delete", { link = "DiffDelete" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { fg = "#7acfff" })
hi(0, "@text.environment.name", { fg = "#00c4e1" })
hi(0, "@text.literal", { fg = "#94d243" })
hi(0, "@text.literal.markdown_inline", { bg = "#414868", fg = "#70a0ff" })
hi(0, "@text.math", { fg = "#00c4e1" })
hi(0, "@text.note", { fg = "#00c4e1" })
hi(0, "@text.reference", { fg = "#00bd9c" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { bold = true, fg = "#70a0ff" })
hi(0, "@text.todo", { bg = "#e0af68", fg = "#1f254c" })
hi(0, "@text.todo.checked", { fg = "#48e0cc" })
hi(0, "@text.todo.unchecked", { fg = "#70a0ff" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { underline = true })
hi(0, "@text.warning", { bg = "#e0af68", fg = "#1f254c" })
hi(0, "@type", { fg = "#00c4e1" })
hi(0, "@type.builtin", { fg = "#00a5c1" })
hi(0, "@type.definition", { fg = "#00c4e1" })
hi(0, "@type.qualifier", { fg = "#a272ee" })
hi(0, "@variable", { fg = "#bdc9ff" })
hi(0, "@variable.builtin", { fg = "#ff6588" })
hi(0, "ALEErrorSign", { fg = "#ef2637" })
hi(0, "ALEWarningSign", { fg = "#ecab44" })
hi(0, "ActionFix", { fg = "#7acfff" })
hi(0, "ActionPreviewBorder", { fg = "#00a5c1" })
hi(0, "ActionPreviewNormal", {})
hi(0, "ActionPreviewTitle", { bold = true, fg = "#70a0ff" })
hi(0, "AlphaButtons", { fg = "#7acfff" })
hi(0, "AlphaFooter", { fg = "#00c4e1" })
hi(0, "AlphaHeader", { fg = "#70a0ff" })
hi(0, "AlphaHeaderLabel", { fg = "#ff9c5d" })
hi(0, "AlphaShortcut", { fg = "#ff9c5d" })
hi(0, "Bold", { bold = true })
hi(0, "BufferAlternate", { bg = "#3b4261", fg = "#bdc9ff" })
hi(0, "BufferAlternateADDED", {})
hi(0, "BufferAlternateCHANGED", {})
hi(0, "BufferAlternateDELETED", {})
hi(0, "BufferAlternateERROR", { bg = "#3b4261", fg = "#ef2637" })
hi(0, "BufferAlternateHINT", { bg = "#3b4261", fg = "#00bd9c" })
hi(0, "BufferAlternateINFO", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferAlternateIcon", { bg = "#3b4261", fg = "#bdc9ff" })
hi(0, "BufferAlternateIndex", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferAlternateMod", { bg = "#3b4261", fg = "#ecab44" })
hi(0, "BufferAlternateNumber", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferAlternateSign", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferAlternateSignRight", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferAlternateTarget", { bg = "#3b4261", fg = "#ff6588" })
hi(0, "BufferAlternateWARN", { bg = "#3b4261", fg = "#ecab44" })
hi(0, "BufferCurrent", { bg = "#24283b", fg = "#bdc9ff" })
hi(0, "BufferCurrentADDED", { bg = "#7aa2f7", ctermfg = 82, fg = "#006f6c" })
hi(0, "BufferCurrentCHANGED", { bg = "#7aa2f7", ctermfg = 75, fg = "#4269bb" })
hi(0, "BufferCurrentDELETED", { bg = "#7aa2f7", ctermfg = 124, fg = "#c44150" })
hi(0, "BufferCurrentERROR", { bg = "#24283b", fg = "#ef2637" })
hi(0, "BufferCurrentHINT", { bg = "#24283b", fg = "#00bd9c" })
hi(0, "BufferCurrentINFO", { bg = "#24283b", fg = "#00b9d8" })
hi(0, "BufferCurrentIcon", { bg = "#24283b", fg = "#bdc9ff" })
hi(0, "BufferCurrentIndex", { bg = "#24283b", fg = "#00b9d8" })
hi(0, "BufferCurrentMod", { bg = "#24283b", fg = "#ecab44" })
hi(0, "BufferCurrentNumber", { bg = "#24283b", fg = "#00b9d8" })
hi(0, "BufferCurrentSign", { bg = "#24283b", fg = "#1f254c" })
hi(0, "BufferCurrentSignRight", { bg = "#24283b", fg = "#1f254c" })
hi(0, "BufferCurrentTarget", { bg = "#24283b", fg = "#ff6588" })
hi(0, "BufferCurrentWARN", { bg = "#24283b", fg = "#ecab44" })
hi(0, "BufferDefaultAlternateIcon", { bg = "#3b4261", fg = "#bdc9ff" })
hi(0, "BufferDefaultAlternateNumber", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferDefaultAlternateSignRight", { bg = "#3b4261", fg = "#00b9d8" })
hi(0, "BufferDefaultCurrent", { bg = "#7aa2f7", ctermfg = 255, fg = "#191e3d" })
hi(0, "BufferDefaultCurrentADDED", { bg = "#7aa2f7", ctermfg = 82, fg = "#006f6c" })
hi(0, "BufferDefaultCurrentCHANGED", { bg = "#7aa2f7", ctermfg = 75, fg = "#4269bb" })
hi(0, "BufferDefaultCurrentDELETED", { bg = "#7aa2f7", ctermfg = 124, fg = "#c44150" })
hi(0, "BufferDefaultCurrentERROR", { bg = "#7aa2f7", ctermfg = 124, fg = "#ef2637" })
hi(0, "BufferDefaultCurrentHINT", { bg = "#7aa2f7", ctermfg = 168, fg = "#00bd9c" })
hi(0, "BufferDefaultCurrentINFO", { bg = "#7aa2f7", ctermfg = 217, fg = "#00b9d8" })
hi(0, "BufferDefaultCurrentIcon", { bg = "#24283b", fg = "#bdc9ff" })
hi(0, "BufferDefaultCurrentIndex", { bg = "#7aa2f7", ctermfg = 75, fg = "#00c4e1" })
hi(0, "BufferDefaultCurrentMod", { bg = "#7aa2f7", ctermfg = 178, fg = "#ecab44" })
hi(0, "BufferDefaultCurrentNumber", { bg = "#24283b", fg = "#00b9d8" })
hi(0, "BufferDefaultCurrentSign", { bg = "#7aa2f7", ctermfg = 75, fg = "#00c4e1" })
hi(0, "BufferDefaultCurrentSignRight", { bg = "#24283b", fg = "#1f254c" })
hi(0, "BufferDefaultCurrentTarget", { bg = "#7aa2f7", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultCurrentWARN", { bg = "#7aa2f7", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferDefaultInactive", { bg = "#1f2335", ctermfg = 255, fg = "#343d7a" })
hi(0, "BufferDefaultInactiveADDED", { bg = "#1f2335", ctermfg = 82, fg = "#006f6c" })
hi(0, "BufferDefaultInactiveCHANGED", { bg = "#1f2335", ctermfg = 75, fg = "#4269bb" })
hi(0, "BufferDefaultInactiveDELETED", { bg = "#1f2335", ctermfg = 124, fg = "#c44150" })
hi(0, "BufferDefaultInactiveERROR", { bg = "#1f2335", ctermfg = 124, fg = "#ef2637" })
hi(0, "BufferDefaultInactiveHINT", { bg = "#1f2335", ctermfg = 168, fg = "#00bd9c" })
hi(0, "BufferDefaultInactiveINFO", { bg = "#1f2335", ctermfg = 217, fg = "#00b9d8" })
hi(0, "BufferDefaultInactiveIcon", { bg = "#262a3e", fg = "#5b66ab" })
hi(0, "BufferDefaultInactiveIndex", { bg = "#1f2335", ctermfg = 240, fg = "#4b579e" })
hi(0, "BufferDefaultInactiveMod", { bg = "#1f2335", ctermfg = 178, fg = "#ecab44" })
hi(0, "BufferDefaultInactiveNumber", { bg = "#262a3e", fg = "#6c76bd" })
hi(0, "BufferDefaultInactiveSign", { bg = "#1f2335", ctermfg = 240, fg = "#4b579e" })
hi(0, "BufferDefaultInactiveSignRight", { bg = "#262a3e", fg = "#1f254c" })
hi(0, "BufferDefaultInactiveTarget", { bg = "#1f2335", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultInactiveWARN", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferDefaultOffset", { bg = "#282d41", fg = "#6c76bd" })
hi(0, "BufferDefaultTabpageFill", { bg = "#1d202f", ctermfg = 102, fg = "#a4afe7" })
hi(0, "BufferDefaultTabpages", { bg = "#1d202f", bold = true, ctermfg = 75, fg = "#ff9c5d" })
hi(0, "BufferDefaultTabpagesSep", { bg = "#1d202f", bold = true, ctermfg = 255, fg = "#00c4e1" })
hi(0, "BufferDefaultVisible", { bg = "#1f2335", ctermfg = 255, fg = "#343d7a" })
hi(0, "BufferDefaultVisibleADDED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferDefaultVisibleCHANGED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferDefaultVisibleDELETED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferDefaultVisibleERROR", { bg = "#1f2335", ctermfg = 124, fg = "#ef2637" })
hi(0, "BufferDefaultVisibleHINT", { bg = "#1f2335", ctermfg = 168, fg = "#00bd9c" })
hi(0, "BufferDefaultVisibleINFO", { bg = "#1f2335", ctermfg = 217, fg = "#00b9d8" })
hi(0, "BufferDefaultVisibleIcon", { bg = "#1f2335", fg = "#bdc9ff" })
hi(0, "BufferDefaultVisibleIndex", { bg = "#1f2335", ctermfg = 255, fg = "#343d7a" })
hi(0, "BufferDefaultVisibleMod", { bg = "#1f2335", ctermfg = 178, fg = "#ecab44" })
hi(0, "BufferDefaultVisibleNumber", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferDefaultVisibleSign", { bg = "#1f2335", ctermfg = 255, fg = "#343d7a" })
hi(0, "BufferDefaultVisibleSignRight", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferDefaultVisibleTarget", { bg = "#1f2335", bold = true, ctermfg = 9, fg = "#ff0000" })
hi(0, "BufferDefaultVisibleWARN", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferInactive", { bg = "#262a3e", fg = "#5b66ab" })
hi(0, "BufferInactiveADDED", { bg = "#1f2335", ctermfg = 82, fg = "#006f6c" })
hi(0, "BufferInactiveCHANGED", { bg = "#1f2335", ctermfg = 75, fg = "#4269bb" })
hi(0, "BufferInactiveDELETED", { bg = "#1f2335", ctermfg = 124, fg = "#c44150" })
hi(0, "BufferInactiveERROR", { bg = "#262a3e", fg = "#c72a3a" })
hi(0, "BufferInactiveHINT", { bg = "#262a3e", fg = "#009f89" })
hi(0, "BufferInactiveINFO", { bg = "#262a3e", fg = "#009cb9" })
hi(0, "BufferInactiveIcon", { bg = "#262a3e", fg = "#5b66ab" })
hi(0, "BufferInactiveIndex", { bg = "#262a3e", fg = "#6c76bd" })
hi(0, "BufferInactiveMod", { bg = "#262a3e", fg = "#c49043" })
hi(0, "BufferInactiveNumber", { bg = "#262a3e", fg = "#6c76bd" })
hi(0, "BufferInactiveSign", { bg = "#262a3e", fg = "#1f254c" })
hi(0, "BufferInactiveSignRight", { bg = "#262a3e", fg = "#1f254c" })
hi(0, "BufferInactiveTarget", { bg = "#262a3e", fg = "#ff6588" })
hi(0, "BufferInactiveWARN", { bg = "#262a3e", fg = "#c49043" })
hi(0, "BufferLineIndicatorSelected", { fg = "#4f81d4" })
hi(0, "BufferOffset", { bg = "#1f2335", fg = "#6c76bd" })
hi(0, "BufferScrollArrow", { bg = "#1d202f", bold = true, ctermfg = 255, fg = "#00c4e1" })
hi(0, "BufferTabpageFill", { bg = "#282d41", fg = "#6c76bd" })
hi(0, "BufferTabpages", { bg = "#1f2335" })
hi(0, "BufferTabpagesSep", { bg = "#1d202f", bold = true, ctermfg = 255, fg = "#00c4e1" })
hi(0, "BufferVisible", { bg = "#1f2335", fg = "#bdc9ff" })
hi(0, "BufferVisibleADDED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferVisibleCHANGED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferVisibleDELETED", { bg = "#1f2335", ctermfg = 208, fg = "#ecab44" })
hi(0, "BufferVisibleERROR", { bg = "#1f2335", fg = "#ef2637" })
hi(0, "BufferVisibleHINT", { bg = "#1f2335", fg = "#00bd9c" })
hi(0, "BufferVisibleINFO", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferVisibleIcon", { bg = "#1f2335", fg = "#bdc9ff" })
hi(0, "BufferVisibleIndex", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferVisibleMod", { bg = "#1f2335", fg = "#ecab44" })
hi(0, "BufferVisibleNumber", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferVisibleSign", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferVisibleSignRight", { bg = "#1f2335", fg = "#00b9d8" })
hi(0, "BufferVisibleTarget", { bg = "#1f2335", fg = "#ff6588" })
hi(0, "BufferVisibleWARN", { bg = "#1f2335", fg = "#ecab44" })
hi(0, "CallHierarchyBorder", { fg = "#00a5c1" })
hi(0, "CallHierarchyIcon", { fg = "#be94ff" })
hi(0, "CallHierarchyNormal", {})
hi(0, "CallHierarchyTitle", { bold = true, fg = "#70a0ff" })
hi(0, "Character", { fg = "#94d243" })
hi(0, "CmpDocumentation", { fg = "#bdc9ff" })
hi(0, "CmpDocumentationBorder", { fg = "#00a5c1" })
hi(0, "CmpGhostText", { fg = "#3a4383" })
hi(0, "CmpItemAbbr", { fg = "#bdc9ff" })
hi(0, "CmpItemAbbrDefault", { fg = "#bdc9ff" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#343d7a", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#4d59a8" })
hi(0, "CmpItemAbbrMatch", { fg = "#00c4e1" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#bdc9ff" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#00c4e1" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#bdc9ff" })
hi(0, "CmpItemKind", { fg = "#00c4e1" })
hi(0, "CmpItemKindClass", { fg = "#ff9c5d" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#00c4e1" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#be94ff" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#70a0ff" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { ctermfg = 6, fg = "#01ff01" })
hi(0, "CmpItemKindDefault", { fg = "#00c4e1" })
hi(0, "CmpItemKindEnum", { fg = "#ff9c5d" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#48e0cc" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#ff9c5d" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#48e0cc" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#00c4e1" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#00c4e1" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#70a0ff" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#ff9c5d" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#7acfff" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#70a0ff" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#ecab44" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#48e0cc" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#48e0cc" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#be94ff" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#6c76bd" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#ff9c5d" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#00c4e1" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#48e0cc" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#ff9c5d" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#be94ff" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#be94ff" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#4d59a8" })
hi(0, "CmpItemMenuDefault", { fg = "#bdc9ff" })
hi(0, "CodeActionBorder", { fg = "#00a5c1" })
hi(0, "CodeActionNormal", {})
hi(0, "CodeActionNumber", { bg = "#283b4d" })
hi(0, "CodeActionText", { fg = "#bdc9ff" })
hi(0, "ColorColumn", { bg = "#1d202f" })
hi(0, "Comment", { fg = "#4d59a8" })
hi(0, "Conceal", { fg = "#6c76bd" })
hi(0, "Constant", { fg = "#ff9c5d" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#c0caf5", fg = "#1f254c" })
hi(0, "CursorColumn", { bg = "#292e42" })
hi(0, "CursorIM", { bg = "#c0caf5", fg = "#1f254c" })
hi(0, "CursorLine", { bg = "#292e42" })
hi(0, "CursorLineNr", { fg = "#6c76bd" })
hi(0, "DapStoppedLine", { bg = "#373640" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#424242" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsPath", { fg = "#00f1f5" })
hi(0, "DapUIDecoration", { fg = "#00f1f5" })
hi(0, "DapUIFloatBorder", { fg = "#00f1f5" })
hi(0, "DapUILineNumber", { fg = "#00f1f5" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#00f1f5" })
hi(0, "DapUINormalNC", {})
hi(0, "DapUIPlayPause", { fg = "#a5ff5e" })
hi(0, "DapUIPlayPauseNC", { fg = "#a5ff5e" })
hi(0, "DapUIRestart", { fg = "#a5ff5e" })
hi(0, "DapUIRestartNC", { fg = "#a5ff5e" })
hi(0, "DapUIScope", { fg = "#00f1f5" })
hi(0, "DapUISource", { fg = "#d680ff" })
hi(0, "DapUIStepBack", { fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { fg = "#00f1f5" })
hi(0, "DapUIStepInto", { fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOut", { fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOver", { fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { fg = "#00f1f5" })
hi(0, "DapUIStop", { fg = "#f70067" })
hi(0, "DapUIStopNC", { fg = "#f70067" })
hi(0, "DapUIStoppedThread", { fg = "#00f1f5" })
hi(0, "DapUIThread", { fg = "#a5ff5e" })
hi(0, "DapUIType", { fg = "#d680ff" })
hi(0, "DapUIUnavailable", { fg = "#424242" })
hi(0, "DapUIUnavailableNC", { fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { fg = "#f70067" })
hi(0, "DapUIWatchesError", { fg = "#f70067" })
hi(0, "DapUIWatchesValue", { fg = "#a5ff5e" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#be94ff" })
hi(0, "DashboardFooter", { fg = "#ecab44", italic = true })
hi(0, "DashboardHeader", { fg = "#70a0ff" })
hi(0, "DashboardShortCut", { fg = "#7acfff" })
hi(0, "Debug", { fg = "#ff9c5d" })
hi(0, "DefinitionBorder", { fg = "#00a5c1" })
hi(0, "DefinitionCount", { fg = "#a272ee" })
hi(0, "DefinitionIcon", { fg = "#70a0ff" })
hi(0, "DefinitionNormal", {})
hi(0, "DefinitionSearch", { bg = "#3d59a1", fg = "#bdc9ff" })
hi(0, "DiagnosticBorder", { fg = "#00a5c1" })
hi(0, "DiagnosticBufnr", { fg = "#bdc9ff" })
hi(0, "DiagnosticError", { fg = "#ef2637" })
hi(0, "DiagnosticFname", { fg = "#7acfff" })
hi(0, "DiagnosticHint", { fg = "#00bd9c" })
hi(0, "DiagnosticInfo", { fg = "#00b9d8" })
hi(0, "DiagnosticInformation", { link = "DiagnosticInfo" })
hi(0, "DiagnosticNormal", {})
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#6cf671" })
hi(0, "DiagnosticShowBorder", { fg = "#48e0cc" })
hi(0, "DiagnosticShowNormal", {})
hi(0, "DiagnosticSource", { fg = "#4d59a8" })
hi(0, "DiagnosticUnderlineError", { sp = "#db4b4b", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#1abc9c", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e0af68", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#3a4383" })
hi(0, "DiagnosticVirtualTextError", { bg = "#362c3d", fg = "#ef2637" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#233745", fg = "#00bd9c" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#22374b", fg = "#00b9d8" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#373640", fg = "#ecab44" })
hi(0, "DiagnosticWarn", { fg = "#ecab44" })
hi(0, "DiagnosticWarning", { link = "DiagnosticWarn" })
hi(0, "DiffAdd", { bg = "#283b4d" })
hi(0, "DiffChange", { bg = "#272d43" })
hi(0, "DiffDelete", { bg = "#3f2d3d" })
hi(0, "DiffText", { bg = "#394b70" })
hi(0, "Directory", { fg = "#70a0ff" })
hi(0, "EndOfBuffer", { fg = "#1f254c" })
hi(0, "Error", { fg = "#ef2637" })
hi(0, "ErrorMsg", { fg = "#ef2637" })
hi(0, "FernBranchText", { fg = "#70a0ff" })
hi(0, "FinderBorder", { fg = "#00a5c1" })
hi(0, "FinderCode", { fg = "#4d59a8" })
hi(0, "FinderCount", { fg = "#ff9c5d" })
hi(0, "FinderIcon", { fg = "#00c4e1" })
hi(0, "FinderLines", { fg = "#86ddff" })
hi(0, "FinderNormal", {})
hi(0, "FinderPreview", { bg = "#3d59a1", fg = "#bdc9ff" })
hi(0, "FinderPreviewBorder", { fg = "#00a5c1" })
hi(0, "FinderSelection", { fg = "#94d243" })
hi(0, "FinderSpinner", { fg = "#be94ff" })
hi(0, "FinderSpinnerTitle", { fg = "#be94ff" })
hi(0, "FinderStart", { fg = "#70a0ff" })
hi(0, "FinderType", { fg = "#48e0cc" })
hi(0, "FlashBackdrop", { fg = "#4b579e" })
hi(0, "FlashLabel", { bg = "#ff007c", bold = true, fg = "#bdc9ff" })
hi(0, "FloatBorder", { fg = "#00a5c1" })
hi(0, "FloatTitle", { fg = "#00a5c1" })
hi(0, "FlutterToolsOutlineIndentGuides", { fg = "#4b579e" })
hi(0, "FoldColumn", { fg = "#4d59a8" })
hi(0, "Folded", { bg = "#3b4261", fg = "#70a0ff" })
hi(0, "Foo", { bg = "#ff007c", fg = "#bdc9ff" })
hi(0, "Function", { fg = "#70a0ff" })
hi(0, "GitGutterAdd", { fg = "#006f6c" })
hi(0, "GitGutterAddLineNr", { fg = "#006f6c" })
hi(0, "GitGutterChange", { fg = "#4269bb" })
hi(0, "GitGutterChangeLineNr", { fg = "#4269bb" })
hi(0, "GitGutterDelete", { fg = "#c44150" })
hi(0, "GitGutterDeleteLineNr", { fg = "#c44150" })
hi(0, "GitSignsAdd", { fg = "#006f6c" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#283b4d" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { fg = "#006f6c" })
hi(0, "GitSignsAddPreview", { bg = "#283b4d" })
hi(0, "GitSignsChange", { fg = "#4269bb" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#272d43" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { fg = "#4269bb" })
hi(0, "GitSignsChangedelete", { fg = "#4269bb" })
hi(0, "GitSignsChangedeleteLn", { bg = "#272d43" })
hi(0, "GitSignsChangedeleteNr", { fg = "#4269bb" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#4b579e" })
hi(0, "GitSignsDelete", { fg = "#c44150" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { fg = "#c44150" })
hi(0, "GitSignsDeletePreview", { bg = "#3f2d3d" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#3f2d3d" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { fg = "#033736" })
hi(0, "GitSignsStagedAddLn", { bg = "#283b4d" })
hi(0, "GitSignsStagedAddNr", { fg = "#033736" })
hi(0, "GitSignsStagedChange", { fg = "#1f3460" })
hi(0, "GitSignsStagedChangeLn", { bg = "#272d43" })
hi(0, "GitSignsStagedChangeNr", { fg = "#1f3460" })
hi(0, "GitSignsStagedChangedelete", { fg = "#1f3460" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#272d43" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#1f3460" })
hi(0, "GitSignsStagedDelete", { fg = "#632027" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#632027" })
hi(0, "GitSignsStagedTopdelete", { fg = "#632027" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#632027" })
hi(0, "GitSignsTopdelete", { fg = "#c44150" })
hi(0, "GitSignsTopdeleteNr", { fg = "#c44150" })
hi(0, "GitSignsUntracked", { fg = "#006f6c" })
hi(0, "GitSignsUntrackedLn", { bg = "#283b4d" })
hi(0, "GitSignsUntrackedNr", { fg = "#006f6c" })
hi(0, "GitSignsVirtLnum", { bg = "#3f2d3d" })
hi(0, "GlyphPalette1", { fg = "#ef2637" })
hi(0, "GlyphPalette2", { fg = "#94d243" })
hi(0, "GlyphPalette3", { fg = "#ecab44" })
hi(0, "GlyphPalette4", { fg = "#70a0ff" })
hi(0, "GlyphPalette6", { fg = "#48e0cc" })
hi(0, "GlyphPalette7", { fg = "#bdc9ff" })
hi(0, "GlyphPalette9", { fg = "#ff6588" })
hi(0, "Hlargs", { fg = "#ecab44" })
hi(0, "HopNextKey", { bold = true, fg = "#ff007c" })
hi(0, "HopNextKey1", { bold = true, fg = "#00b9d8" })
hi(0, "HopNextKey2", { fg = "#027f9b" })
hi(0, "HopUnmatched", { fg = "#4b579e" })
hi(0, "HoverBorder", { fg = "#00a5c1" })
hi(0, "HoverNormal", {})
hi(0, "Identifier", { fg = "#be94ff" })
hi(0, "IlluminatedWordRead", { bg = "#3b4261" })
hi(0, "IlluminatedWordText", { bg = "#3b4261" })
hi(0, "IlluminatedWordWrite", { bg = "#3b4261" })
hi(0, "IncSearch", { bg = "#ff9e64", fg = "#191e3d" })
hi(0, "IndentBlanklineChar", { fg = "#343d7a", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#a272ee", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#7acfff" })
hi(0, "LazyProgressDone", { bold = true, fg = "#ff007c" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#343d7a" })
hi(0, "LeapBackdrop", { fg = "#4b579e" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#ff007c" })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#48e0cc" })
hi(0, "LeapMatch", { bg = "#ff007c", bold = true, fg = "#bdc9ff" })
hi(0, "LightspeedGreyWash", { fg = "#4b579e" })
hi(0, "LightspeedLabel", { bold = true, fg = "#ff007c", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#48e0cc", underline = true })
hi(0, "LightspeedLabelDistantOverlapped", { fg = "#02a9bc", underline = true })
hi(0, "LightspeedLabelOverlapped", { fg = "#ff007c", underline = true })
hi(0, "LightspeedMaskedChar", { fg = "#ff9c5d" })
hi(0, "LightspeedOneCharMatch", { bg = "#ff007c", bold = true, fg = "#bdc9ff" })
hi(0, "LightspeedPendingOpArea", { bg = "#ff007c", fg = "#bdc9ff" })
hi(0, "LightspeedShortcut", { bg = "#ff007c", bold = true, fg = "#bdc9ff", underline = true })
hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#00b9d8" })
hi(0, "LineNr", { fg = "#343d7a" })
hi(0, "LspCodeLens", { fg = "#4d59a8" })
hi(0, "LspFloatWinBorder", { fg = "#00a5c1" })
hi(0, "LspInfoBorder", { fg = "#00a5c1" })
hi(0, "LspInfoFiletype", { fg = "#00c4e1" })
hi(0, "LspInfoList", { fg = "#70a0ff" })
hi(0, "LspInfoTip", { fg = "#4d59a8" })
hi(0, "LspInfoTitle", { bold = true, fg = "#70a0ff" })
hi(0, "LspInlayHint", { bg = "#262c40", fg = "#4b579e" })
hi(0, "LspReferenceRead", { bg = "#3b4261" })
hi(0, "LspReferenceText", { bg = "#3b4261" })
hi(0, "LspReferenceWrite", { bg = "#3b4261" })
hi(0, "LspSagaBorderTitle", { fg = "#7acfff" })
hi(0, "LspSagaCodeActionBorder", { fg = "#70a0ff" })
hi(0, "LspSagaCodeActionContent", { fg = "#a272ee" })
hi(0, "LspSagaCodeActionTitle", { fg = "#00c4e1" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#94d243" })
hi(0, "LspSagaFinderSelection", { fg = "#24377d" })
hi(0, "LspSagaHoverBorder", { fg = "#70a0ff" })
hi(0, "LspSagaRenameBorder", { fg = "#94d243" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#ff6588" })
hi(0, "LspSignatureActiveParameter", { bg = "#28304b", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#ff9c5d" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#3b4261" })
hi(0, "MiniCursorwordCurrent", { bg = "#3b4261" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#00c4e1", nocombine = true })
hi(0, "MiniJump", { bg = "#ff007c", fg = "#ffffff" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#ff007c", nocombine = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#ecab44", italic = true })
hi(0, "MiniStarterHeader", { fg = "#70a0ff" })
hi(0, "MiniStarterInactive", { fg = "#4d59a8" })
hi(0, "MiniStarterItem", { fg = "#bdc9ff" })
hi(0, "MiniStarterItemBullet", { fg = "#00a5c1" })
hi(0, "MiniStarterItemPrefix", { fg = "#ecab44" })
hi(0, "MiniStarterQuery", { fg = "#00b9d8" })
hi(0, "MiniStarterSection", { fg = "#00c4e1" })
hi(0, "MiniStatuslineDevinfo", { bg = "#292e42", fg = "#a4afe7" })
hi(0, "MiniStatuslineFileinfo", { bg = "#292e42", fg = "#a4afe7" })
hi(0, "MiniStatuslineFilename", { bg = "#3b4261", fg = "#a4afe7" })
hi(0, "MiniStatuslineInactive", { bg = "#1f2335", fg = "#70a0ff" })
hi(0, "MiniStatuslineModeCommand", { bg = "#e0af68", bold = true, fg = "#191e3d" })
hi(0, "MiniStatuslineModeInsert", { bg = "#9ece6a", bold = true, fg = "#191e3d" })
hi(0, "MiniStatuslineModeNormal", { bg = "#7aa2f7", bold = true, fg = "#191e3d" })
hi(0, "MiniStatuslineModeOther", { bg = "#1abc9c", bold = true, fg = "#191e3d" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f7768e", bold = true, fg = "#191e3d" })
hi(0, "MiniStatuslineModeVisual", { bg = "#bb9af7", bold = true, fg = "#191e3d" })
hi(0, "MiniSurround", { bg = "#ff9e64", fg = "#191e3d" })
hi(0, "MiniTablineCurrent", { bg = "#3b4261", fg = "#bdc9ff" })
hi(0, "MiniTablineFill", { bg = "#1d202f" })
hi(0, "MiniTablineHidden", { bg = "#1f2335", fg = "#6c76bd" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#3b4261", fg = "#ecab44" })
hi(0, "MiniTablineModifiedHidden", { bg = "#1f2335", fg = "#b28443" })
hi(0, "MiniTablineModifiedVisible", { bg = "#1f2335", fg = "#ecab44" })
hi(0, "MiniTablineTabpagesection", { bg = "#1f2335" })
hi(0, "MiniTablineVisible", { bg = "#1f2335", fg = "#bdc9ff" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff6588" })
hi(0, "MiniTestPass", { bold = true, fg = "#94d243" })
hi(0, "MiniTrailspace", { bg = "#f7768e" })
hi(0, "ModeMsg", { bold = true, fg = "#a4afe7" })
hi(0, "MoreMsg", { fg = "#70a0ff" })
hi(0, "MsgArea", { fg = "#a4afe7" })
hi(0, "MyCopilotIcon", { fg = "#ffa509" })
hi(0, "NavicIconsArray", { fg = "#ff9c5d" })
hi(0, "NavicIconsBoolean", { fg = "#ff9c5d" })
hi(0, "NavicIconsClass", { fg = "#ff9c5d" })
hi(0, "NavicIconsConstant", { fg = "#be94ff" })
hi(0, "NavicIconsConstructor", { fg = "#ff9c5d" })
hi(0, "NavicIconsEnum", { fg = "#ff9c5d" })
hi(0, "NavicIconsEnumMember", { fg = "#48e0cc" })
hi(0, "NavicIconsEvent", { fg = "#ff9c5d" })
hi(0, "NavicIconsField", { fg = "#48e0cc" })
hi(0, "NavicIconsFile", { fg = "#bdc9ff" })
hi(0, "NavicIconsFunction", { fg = "#70a0ff" })
hi(0, "NavicIconsInterface", { fg = "#ff9c5d" })
hi(0, "NavicIconsKey", { fg = "#a272ee" })
hi(0, "NavicIconsKeyword", { fg = "#a272ee" })
hi(0, "NavicIconsMethod", { fg = "#70a0ff" })
hi(0, "NavicIconsModule", { fg = "#ecab44" })
hi(0, "NavicIconsNamespace", { fg = "#bdc9ff" })
hi(0, "NavicIconsNull", { fg = "#ff9c5d" })
hi(0, "NavicIconsNumber", { fg = "#ff9c5d" })
hi(0, "NavicIconsObject", { fg = "#ff9c5d" })
hi(0, "NavicIconsOperator", { fg = "#bdc9ff" })
hi(0, "NavicIconsPackage", { fg = "#bdc9ff" })
hi(0, "NavicIconsProperty", { fg = "#48e0cc" })
hi(0, "NavicIconsString", { fg = "#94d243" })
hi(0, "NavicIconsStruct", { fg = "#ff9c5d" })
hi(0, "NavicIconsTypeParameter", { fg = "#48e0cc" })
hi(0, "NavicIconsVariable", { fg = "#be94ff" })
hi(0, "NavicSeparator", { fg = "#bdc9ff" })
hi(0, "NavicText", { fg = "#bdc9ff" })
hi(0, "NeoTreeDimText", { fg = "#343d7a" })
hi(0, "NeoTreeNormal", { fg = "#a4afe7" })
hi(0, "NeoTreeNormalNC", { fg = "#a4afe7" })
hi(0, "NeogitBranch", { fg = "#be94ff" })
hi(0, "NeogitDiffAddHighlight", { bg = "#283b4d", fg = "#13a0b2" })
hi(0, "NeogitDiffContextHighlight", { bg = "#30354e", fg = "#a4afe7" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#3f2d3d", fg = "#a13d4d" })
hi(0, "NeogitHunkHeader", { bg = "#292e42", fg = "#bdc9ff" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3b4261", fg = "#70a0ff" })
hi(0, "NeogitRemote", { fg = "#a272ee" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#a272ee" })
hi(0, "NeotestBorder", { fg = "#70a0ff" })
hi(0, "NeotestDir", { fg = "#70a0ff" })
hi(0, "NeotestExpandMarker", { fg = "#a4afe7" })
hi(0, "NeotestFailed", { fg = "#ff6588" })
hi(0, "NeotestFile", { fg = "#00bd9c" })
hi(0, "NeotestFocused", { fg = "#ecab44" })
hi(0, "NeotestIndent", { fg = "#a4afe7" })
hi(0, "NeotestMarked", { fg = "#70a0ff" })
hi(0, "NeotestNamespace", { fg = "#02a9bc" })
hi(0, "NeotestPassed", { fg = "#94d243" })
hi(0, "NeotestRunning", { fg = "#ecab44" })
hi(0, "NeotestSkipped", { fg = "#70a0ff" })
hi(0, "NeotestTarget", { fg = "#70a0ff" })
hi(0, "NeotestTest", { fg = "#a4afe7" })
hi(0, "NeotestWinSelect", { fg = "#70a0ff" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#be94ff" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#70a0ff" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#a4afe7" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#48e0cc" })
hi(0, "NoiceCompletionItemKindEvent", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindField", { fg = "#48e0cc" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#70a0ff" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#7acfff" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#70a0ff" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#ecab44" })
hi(0, "NoiceCompletionItemKindOperator", { fg = "#48e0cc" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#48e0cc" })
hi(0, "NoiceCompletionItemKindReference", { fg = "#be94ff" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#6c76bd" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindTypeParameter", { fg = "#48e0cc" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#ff9c5d" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#be94ff" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#be94ff" })
hi(0, "NonText", { fg = "#4b579e" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#bdc9ff" })
hi(0, "NormalSB", { fg = "#a4afe7" })
hi(0, "NotifyDEBUGBody", { fg = "#bdc9ff" })
hi(0, "NotifyDEBUGBorder", { fg = "#2c3568" })
hi(0, "NotifyDEBUGIcon", { fg = "#4d59a8" })
hi(0, "NotifyDEBUGTitle", { fg = "#4d59a8" })
hi(0, "NotifyERRORBody", { fg = "#bdc9ff" })
hi(0, "NotifyERRORBorder", { fg = "#66293f" })
hi(0, "NotifyERRORIcon", { fg = "#ef2637" })
hi(0, "NotifyERRORTitle", { fg = "#ef2637" })
hi(0, "NotifyINFOBody", { fg = "#bdc9ff" })
hi(0, "NotifyINFOBorder", { fg = "#005570" })
hi(0, "NotifyINFOIcon", { fg = "#00b9d8" })
hi(0, "NotifyINFOTitle", { fg = "#00b9d8" })
hi(0, "NotifyTRACEBody", { fg = "#bdc9ff" })
hi(0, "NotifyTRACEBorder", { fg = "#493a80" })
hi(0, "NotifyTRACEIcon", { fg = "#a272ee" })
hi(0, "NotifyTRACETitle", { fg = "#a272ee" })
hi(0, "NotifyWARNBody", { fg = "#bdc9ff" })
hi(0, "NotifyWARNBorder", { fg = "#654e3d" })
hi(0, "NotifyWARNIcon", { fg = "#ecab44" })
hi(0, "NotifyWARNTitle", { fg = "#ecab44" })
hi(0, "NullLsInfoBorder", {})
hi(0, "NullLsInfoHeader", { fg = "#be94ff" })
hi(0, "NullLsInfoSources", { bold = true, fg = "#70a0ff" })
hi(0, "NullLsInfoTitle", { fg = "#00c4e1" })
hi(0, "NvimTreeBookmark", { fg = "#94d243" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#94d243" })
hi(0, "NvimTreeFolderIcon", { fg = "#70a0ff" })
hi(0, "NvimTreeGitDeleted", { fg = "#a13d4d" })
hi(0, "NvimTreeGitDirty", { fg = "#4f81d4" })
hi(0, "NvimTreeGitMerge", { fg = "#ecab44" })
hi(0, "NvimTreeGitNew", { fg = "#13a0b2" })
hi(0, "NvimTreeGitRenamed", { fg = "#be94ff" })
hi(0, "NvimTreeGitStaged", { fg = "#94d243" })
hi(0, "NvimTreeImageFile", { fg = "#a4afe7" })
hi(0, "NvimTreeIndentMarker", { fg = "#343d7a" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#be94ff" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeNormal", { fg = "#a4afe7" })
hi(0, "NvimTreeNormalNC", { fg = "#a4afe7" })
hi(0, "NvimTreeOpenedFile", { bg = "#292e42" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#70a0ff" })
hi(0, "NvimTreeSpecialFile", { fg = "#a272ee", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#70a0ff" })
hi(0, "NvimTreeWinSeparator", { fg = "#191e3d" })
hi(0, "NvimTreeWindowPicker", { bg = "#4493c8", bold = true, fg = "#ededed" })
hi(0, "Operator", { fg = "#86ddff" })
hi(0, "OutlineIndent", { fg = "#8762b9" })
hi(0, "OutlinePreviewBorder", {})
hi(0, "OutlinePreviewNormal", { fg = "#00a5c1" })
hi(0, "OutlineWinSeparator", { bold = true, fg = "#191e3d" })
hi(0, "Pmenu", { bg = "#1f2335", fg = "#bdc9ff" })
hi(0, "PmenuSbar", { bg = "#2a2e3f" })
hi(0, "PmenuSel", { bg = "#363d59" })
hi(0, "PmenuThumb", { bg = "#3b4261" })
hi(0, "PreProc", { fg = "#7acfff" })
hi(0, "Question", { fg = "#70a0ff" })
hi(0, "QuickFixLine", { bg = "#2e3c64", bold = true })
hi(0, "ReferencesCount", { fg = "#a272ee" })
hi(0, "ReferencesIcon", { fg = "#70a0ff" })
hi(0, "RenameBorder", { fg = "#00a5c1" })
hi(0, "RenameMatch", { bg = "#3d59a1", fg = "#bdc9ff" })
hi(0, "RenameNormal", { fg = "#be94ff" })
hi(0, "SagaBeacon", { bg = "#c43963" })
hi(0, "SagaBorder", { fg = "#00a5c1" })
hi(0, "SagaCollapse", { fg = "#38507f" })
hi(0, "SagaCount", { fg = "#4d59a8" })
hi(0, "SagaExpand", { fg = "#38507f" })
hi(0, "SagaLightBulb", { fg = "#00bd9c" })
hi(0, "SagaShadow", { bg = "#000000", blend = 80 })
hi(0, "SagaWinbarArray", { fg = "#00c4e1" })
hi(0, "SagaWinbarBoolean", { fg = "#ff9c5d" })
hi(0, "SagaWinbarClass", { fg = "#7acfff" })
hi(0, "SagaWinbarConstant", { fg = "#ff9c5d" })
hi(0, "SagaWinbarConstructor", { fg = "#be94ff" })
hi(0, "SagaWinbarEnum", { fg = "#ff9c5d" })
hi(0, "SagaWinbarEnumMember", { fg = "#ff9c5d" })
hi(0, "SagaWinbarEvent", { fg = "#ff9c5d" })
hi(0, "SagaWinbarField", { fg = "#48e0cc" })
hi(0, "SagaWinbarFile", { fg = "#00c4e1" })
hi(0, "SagaWinbarFileIcon", { fg = "#01589d" })
hi(0, "SagaWinbarFilename", { fg = "#bac3a1" })
hi(0, "SagaWinbarFolder", { bold = true, fg = "#70a0ff" })
hi(0, "SagaWinbarFolderName", { fg = "#bac3a1" })
hi(0, "SagaWinbarFunction", { fg = "#70a0ff" })
hi(0, "SagaWinbarInterface", { fg = "#00c4e1" })
hi(0, "SagaWinbarKey", { fg = "#ff9c5d" })
hi(0, "SagaWinbarMacro", { fg = "#7acfff" })
hi(0, "SagaWinbarMethod", { fg = "#70a0ff" })
hi(0, "SagaWinbarModule", { fg = "#be94ff" })
hi(0, "SagaWinbarNamespace", { fg = "#7acfff" })
hi(0, "SagaWinbarNull", { fg = "#ff9c5d" })
hi(0, "SagaWinbarNumber", { fg = "#ff9c5d" })
hi(0, "SagaWinbarObject", { fg = "#00c4e1" })
hi(0, "SagaWinbarOperator", { fg = "#86ddff" })
hi(0, "SagaWinbarPackage", { fg = "#be94ff" })
hi(0, "SagaWinbarParameter", { fg = "#ecab44" })
hi(0, "SagaWinbarProperty", { fg = "#48e0cc" })
hi(0, "SagaWinbarSep", { fg = "#86ddff" })
hi(0, "SagaWinbarSnippet", { fg = "#bdc9ff" })
hi(0, "SagaWinbarStaticMethod", { fg = "#70a0ff" })
hi(0, "SagaWinbarString", { fg = "#94d243" })
hi(0, "SagaWinbarStruct", { fg = "#00c4e1" })
hi(0, "SagaWinbarText", { fg = "#94d243" })
hi(0, "SagaWinbarTypeAlias", { fg = "#00c4e1" })
hi(0, "SagaWinbarTypeParameter", { fg = "#ecab44" })
hi(0, "SagaWinbarUnit", { fg = "#ff9c5d" })
hi(0, "SagaWinbarValue", { fg = "#bdc9ff" })
hi(0, "SagaWinbarVariable", { fg = "#bdc9ff" })
hi(0, "ScrollbarError", { fg = "#ef2637" })
hi(0, "ScrollbarErrorHandle", { bg = "#292e42", fg = "#ef2637" })
hi(0, "ScrollbarHandle", { bg = "#292e42" })
hi(0, "ScrollbarHint", { fg = "#00bd9c" })
hi(0, "ScrollbarHintHandle", { bg = "#292e42", fg = "#00bd9c" })
hi(0, "ScrollbarInfo", { fg = "#00b9d8" })
hi(0, "ScrollbarInfoHandle", { bg = "#292e42", fg = "#00b9d8" })
hi(0, "ScrollbarMisc", { fg = "#a272ee" })
hi(0, "ScrollbarMiscHandle", { bg = "#292e42", fg = "#a272ee" })
hi(0, "ScrollbarSearch", { fg = "#ff9c5d" })
hi(0, "ScrollbarSearchHandle", { bg = "#292e42", fg = "#ff9c5d" })
hi(0, "ScrollbarWarn", { fg = "#ecab44" })
hi(0, "ScrollbarWarnHandle", { bg = "#292e42", fg = "#ecab44" })
hi(0, "Search", { bg = "#3d59a1", fg = "#bdc9ff" })
hi(0, "SignColumn", { fg = "#343d7a" })
hi(0, "SignColumnSB", { fg = "#343d7a" })
hi(0, "Sneak", { bg = "#bb9af7", fg = "#232b55" })
hi(0, "SneakScope", { bg = "#2e3c64" })
hi(0, "Special", { fg = "#00c4e1" })
hi(0, "SpecialKey", { fg = "#4b579e" })
hi(0, "SpellBad", { sp = "#db4b4b", undercurl = true })
hi(0, "SpellCap", { sp = "#e0af68", undercurl = true })
hi(0, "SpellLocal", { sp = "#0db9d7", undercurl = true })
hi(0, "SpellRare", { sp = "#1abc9c", undercurl = true })
hi(0, "Statement", { fg = "#be94ff" })
hi(0, "StatusLine", { bg = "#1f2335", fg = "#a4afe7" })
hi(0, "StatusLineNC", { bg = "#1f2335", fg = "#343d7a" })
hi(0, "String", { fg = "#94d243" })
hi(0, "Substitute", { bg = "#f7768e", fg = "#191e3d" })
hi(0, "TSNodeKey", { bold = true, fg = "#ff007c" })
hi(0, "TSNodeUnmatched", { fg = "#4b579e" })
hi(0, "TSRainbowBlue", { fg = "#70a0ff" })
hi(0, "TSRainbowCyan", { fg = "#7acfff" })
hi(0, "TSRainbowGreen", { fg = "#94d243" })
hi(0, "TSRainbowOrange", { fg = "#ff9c5d" })
hi(0, "TSRainbowRed", { fg = "#ff6588" })
hi(0, "TSRainbowViolet", { fg = "#a272ee" })
hi(0, "TSRainbowYellow", { fg = "#ecab44" })
hi(0, "TabLine", { bg = "#1f2335", fg = "#343d7a" })
hi(0, "TabLineFill", { bg = "#1d202f" })
hi(0, "TabLineSel", { bg = "#7aa2f7", fg = "#191e3d" })
hi(0, "TargetWord", { fg = "#7acfff" })
hi(0, "TelescopeBorder", { fg = "#00a5c1" })
hi(0, "TelescopeMatching", { fg = "#00c4e1" })
hi(0, "TelescopeMultiIcon", { fg = "#be94ff" })
hi(0, "TelescopeMultiSelection", { fg = "#00c4e1" })
hi(0, "TelescopeNormal", {})
hi(0, "TelescopePreviewBlock", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewBorder", { fg = "#00a5c1" })
hi(0, "TelescopePreviewCharDev", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewDate", { fg = "#70a0ff" })
hi(0, "TelescopePreviewDirectory", { fg = "#70a0ff" })
hi(0, "TelescopePreviewExecute", { fg = "#94d243" })
hi(0, "TelescopePreviewGroup", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewHyphen", { fg = "#4b579e" })
hi(0, "TelescopePreviewLine", { bg = "#2e3c64" })
hi(0, "TelescopePreviewLink", { fg = "#00c4e1" })
hi(0, "TelescopePreviewMatch", { bg = "#3d59a1", fg = "#bdc9ff" })
hi(0, "TelescopePreviewMessage", {})
hi(0, "TelescopePreviewMessageFillchar", {})
hi(0, "TelescopePreviewNormal", {})
hi(0, "TelescopePreviewPipe", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewRead", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewSize", { fg = "#94d243" })
hi(0, "TelescopePreviewSocket", { fg = "#be94ff" })
hi(0, "TelescopePreviewSticky", { fg = "#7acfff" })
hi(0, "TelescopePreviewTitle", { fg = "#00a5c1" })
hi(0, "TelescopePreviewUser", { fg = "#ff9c5d" })
hi(0, "TelescopePreviewWrite", { fg = "#be94ff" })
hi(0, "TelescopePromptBorder", { fg = "#00a5c1" })
hi(0, "TelescopePromptCounter", { fg = "#4b579e" })
hi(0, "TelescopePromptNormal", {})
hi(0, "TelescopePromptPrefix", { fg = "#be94ff" })
hi(0, "TelescopePromptTitle", { fg = "#00a5c1" })
hi(0, "TelescopeResultsBorder", { fg = "#00a5c1" })
hi(0, "TelescopeResultsClass", { fg = "#70a0ff" })
hi(0, "TelescopeResultsComment", { fg = "#4d59a8" })
hi(0, "TelescopeResultsConstant", { fg = "#ff9c5d" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#283b4d" })
hi(0, "TelescopeResultsDiffChange", { bg = "#272d43" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#3f2d3d" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#4b579e" })
hi(0, "TelescopeResultsField", { fg = "#70a0ff" })
hi(0, "TelescopeResultsFunction", { fg = "#70a0ff" })
hi(0, "TelescopeResultsIdentifier", { fg = "#be94ff" })
hi(0, "TelescopeResultsLineNr", { fg = "#343d7a" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", {})
hi(0, "TelescopeResultsNumber", { fg = "#ff9c5d" })
hi(0, "TelescopeResultsOperator", { fg = "#86ddff" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#00c4e1" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#00a5c1" })
hi(0, "TelescopeResultsVariable", { fg = "#00c4e1" })
hi(0, "TelescopeSelection", { bg = "#2e3c64" })
hi(0, "TelescopeSelectionCaret", { bg = "#2e3c64" })
hi(0, "TelescopeTitle", { fg = "#00a5c1" })
hi(0, "TerminalBorder", { fg = "#00a5c1" })
hi(0, "TerminalNormal", {})
hi(0, "Title", { bold = true, fg = "#70a0ff" })
hi(0, "TitleIcon", { fg = "#be94ff" })
hi(0, "TitleString", { bold = true, fg = "#70a0ff" })
hi(0, "Todo", { bg = "#e0af68", fg = "#1f254c" })
hi(0, "TreesitterContext", { bg = "#363d59" })
hi(0, "TroubleCount", { bg = "#3b4261", fg = "#be94ff" })
hi(0, "TroubleNormal", { fg = "#a4afe7" })
hi(0, "TroubleText", { fg = "#a4afe7" })
hi(0, "Type", { fg = "#00c4e1" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#191e3d" })
hi(0, "Visual", { bg = "#2e3c64" })
hi(0, "VisualNOS", { bg = "#2e3c64" })
hi(0, "WarningMsg", { fg = "#ecab44" })
hi(0, "WhichKey", { fg = "#7acfff" })
hi(0, "WhichKeyDesc", { fg = "#be94ff" })
hi(0, "WhichKeyGroup", { fg = "#70a0ff" })
hi(0, "WhichKeySeparator", { fg = "#4d59a8" })
hi(0, "WhichKeySeperator", { fg = "#4d59a8" })
hi(0, "WhichKeyValue", { fg = "#6c76bd" })
hi(0, "Whitespace", { fg = "#343d7a" })
hi(0, "WildMenu", { bg = "#2e3c64" })
hi(0, "WinSeparator", { bold = true, fg = "#191e3d" })
hi(0, "YankyPut", { link = "IncSearch" })
hi(0, "YankyYanked", { link = "IncSearch" })
hi(0, "debugBreakpoint", { bg = "#22374b", fg = "#00b9d8" })
hi(0, "diffAdded", { fg = "#13a0b2" })
hi(0, "diffChanged", { fg = "#4f81d4" })
hi(0, "diffFile", { fg = "#70a0ff" })
hi(0, "diffIndexLine", { fg = "#be94ff" })
hi(0, "diffLine", { fg = "#4d59a8" })
hi(0, "diffNewFile", { fg = "#ff9c5d" })
hi(0, "diffOldFile", { fg = "#ecab44" })
hi(0, "diffRemoved", { fg = "#a13d4d" })
hi(0, "healthError", { fg = "#ef2637" })
hi(0, "healthSuccess", { fg = "#48e0cc" })
hi(0, "healthWarning", { fg = "#ecab44" })
hi(0, "helpCommand", { bg = "#414868", fg = "#70a0ff" })
hi(0, "htmlH1", { bold = true, fg = "#be94ff" })
hi(0, "htmlH2", { bold = true, fg = "#70a0ff" })
hi(0, "illuminatedCurWord", { bg = "#3b4261" })
hi(0, "illuminatedWord", { bg = "#3b4261" })
hi(0, "lCursor", { bg = "#c0caf5", fg = "#1f254c" })
hi(0, "lualine_a_command", { bg = "#e0af68", fg = "#191e3d" })
hi(0, "lualine_a_inactive", { bg = "#1f2335", fg = "#70a0ff" })
hi(0, "lualine_a_insert", { bg = "#9ece6a", fg = "#191e3d" })
hi(0, "lualine_a_normal", { bg = "#7aa2f7", fg = "#191e3d" })
hi(0, "lualine_a_replace", { bg = "#f7768e", fg = "#191e3d" })
hi(0, "lualine_a_terminal", { bg = "#73daca", fg = "#191e3d" })
hi(0, "lualine_a_visual", { bg = "#bb9af7", fg = "#191e3d" })
hi(0, "lualine_b_command", { bg = "#3b4261", fg = "#ecab44" })
hi(0, "lualine_b_inactive", { bg = "#1f2335", bold = true, fg = "#343d7a" })
hi(0, "lualine_b_insert", { bg = "#3b4261", fg = "#94d243" })
hi(0, "lualine_b_normal", { bg = "#3b4261", fg = "#70a0ff" })
hi(0, "lualine_b_replace", { bg = "#3b4261", fg = "#ff6588" })
hi(0, "lualine_b_terminal", { bg = "#3b4261", fg = "#48e0cc" })
hi(0, "lualine_b_visual", { bg = "#3b4261", fg = "#be94ff" })
hi(0, "lualine_c_inactive", { bg = "#1f2335", fg = "#343d7a" })
hi(0, "lualine_c_normal", { bg = "#1f2335", fg = "#a4afe7" })
hi(0, "lualine_x_filetype_DevIconDart_command", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_inactive", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_insert", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_normal", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_replace", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_terminal", { bg = "#1f2335", fg = "#01589d" })
hi(0, "lualine_x_filetype_DevIconDart_visual", { bg = "#1f2335", fg = "#01589d" })
hi(0, "markdownCode", { fg = "#00bd9c" })
hi(0, "markdownCodeBlock", { fg = "#00bd9c" })
hi(0, "markdownH1", { bold = true, fg = "#be94ff" })
hi(0, "markdownH2", { bold = true, fg = "#70a0ff" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#ff9c5d" })
hi(0, "markdownLinkText", { fg = "#70a0ff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#414868", fg = "#bdc9ff" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#00bd9c" })
hi(0, "mkdCodeStart", { bold = true, fg = "#00bd9c" })
hi(0, "qfFileName", { fg = "#70a0ff" })
hi(0, "qfLineNr", { fg = "#6c76bd" })
hi(0, "rainbowcol1", { fg = "#ff6588" })
hi(0, "rainbowcol2", { fg = "#ecab44" })
hi(0, "rainbowcol3", { fg = "#94d243" })
hi(0, "rainbowcol4", { fg = "#00bd9c" })
hi(0, "rainbowcol5", { fg = "#70a0ff" })
hi(0, "rainbowcol6", { fg = "#be94ff" })
hi(0, "rainbowcol7", { fg = "#a272ee" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1d202f"
g.terminal_color_1 = "#f7768e"
g.terminal_color_2 = "#9ece6a"
g.terminal_color_3 = "#e0af68"
g.terminal_color_4 = "#7aa2f7"
g.terminal_color_5 = "#bb9af7"
g.terminal_color_6 = "#7dcfff"
g.terminal_color_7 = "#a9b1d6"
g.terminal_color_8 = "#414868"
g.terminal_color_9 = "#f7768e"
g.terminal_color_10 = "#9ece6a"
g.terminal_color_11 = "#e0af68"
g.terminal_color_12 = "#7aa2f7"
g.terminal_color_13 = "#bb9af7"
g.terminal_color_14 = "#7dcfff"
g.terminal_color_15 = "#c0caf5"
